export type DailyPoint={date:string;revenue:number;orders:number;markup:number;averageCheck:number};
export type ChannelDaily={date:string;channel:string;revenue:number;orders:number;markup:number;averageCheck:number;markupPercent:number};
export type HourlyDaily={date:string;hour:number;revenue:number;orders:number;markup:number;averageCheck:number};
export type ProductDaily={date:string;productCode:string;productName:string;category:string;quantity:number;revenue:number;markup:number;markupPercent:number};
export type Payload={ok?:boolean;schemaVersion?:number;updatedAt:string;period:{from:string;to:string};milestones?:{softOpening:string;grandOpening:string};summary:{revenue:number;orders:number;averageCheck:number;markup:number;cost:number;markupPercent:number;identifiedOrders:number;identifiedCustomers:number};daily:DailyPoint[];channelsDaily:ChannelDaily[];hourlyDaily:HourlyDaily[];productsDaily:ProductDaily[]};
export type PeriodKey='today'|'yesterday'|'7d'|'30d'|'current_week'|'previous_week'|'current_month'|'previous_month'|'all';
export type Range={from:Date|null;to:Date|null;comparisonFrom:Date|null;comparisonTo:Date|null;label:string;comparisonLabel:string};
export const PERIODS:Array<{key:PeriodKey;label:string}>=[{key:'today',label:'Сьогодні'},{key:'yesterday',label:'Вчора'},{key:'7d',label:'7 днів'},{key:'30d',label:'30 днів'},{key:'current_week',label:'Поточний тиждень'},{key:'previous_week',label:'Минулий тиждень'},{key:'current_month',label:'Поточний місяць'},{key:'previous_month',label:'Минулий місяць'},{key:'all',label:'Весь період'}];
export const money=(v:number)=>`${new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(v||0)} ₴`;
export const num=(v:number)=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(v||0);
export const pct=(v:number)=>`${(v||0).toFixed(1)}%`;
export const parseDate=(s:string)=>new Date(`${s}T00:00:00`);
const startDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const addDays=(d:Date,n:number)=>{const x=startDay(d);x.setDate(x.getDate()+n);return x};
const startWeek=(d:Date)=>{const x=startDay(d);const wd=x.getDay()||7;x.setDate(x.getDate()-wd+1);return x};
const startMonth=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const endMonth=(d:Date)=>new Date(d.getFullYear(),d.getMonth()+1,0);
export const shortDate=(s:string)=>new Intl.DateTimeFormat('uk-UA',{day:'2-digit',month:'short'}).format(parseDate(s));
export const fullDate=(d:Date|null)=>d?new Intl.DateTimeFormat('uk-UA',{day:'2-digit',month:'short',year:'numeric'}).format(d):'—';
export function buildRange(period:PeriodKey,today:Date):Range{const d=startDay(today);if(period==='today')return{from:d,to:d,comparisonFrom:addDays(d,-1),comparisonTo:addDays(d,-1),label:'Сьогодні',comparisonLabel:'до вчора'};if(period==='yesterday')return{from:addDays(d,-1),to:addDays(d,-1),comparisonFrom:addDays(d,-2),comparisonTo:addDays(d,-2),label:'Вчора',comparisonLabel:'до позавчора'};if(period==='7d'||period==='30d'){const days=period==='7d'?7:30;const from=addDays(d,-(days-1));return{from,to:d,comparisonFrom:addDays(from,-days),comparisonTo:addDays(d,-days),label:`Останні ${days} днів`,comparisonLabel:`до попередніх ${days} днів`}}if(period==='current_week'){const from=startWeek(d);return{from,to:d,comparisonFrom:addDays(from,-7),comparisonTo:addDays(d,-7),label:'Поточний тиждень',comparisonLabel:'до такого ж періоду минулого тижня'}}if(period==='previous_week'){const to=addDays(startWeek(d),-1);return{from:addDays(to,-6),to,comparisonFrom:addDays(to,-13),comparisonTo:addDays(to,-7),label:'Минулий тиждень',comparisonLabel:'до тижня перед ним'}}if(period==='current_month'){const pm=new Date(d.getFullYear(),d.getMonth()-1,1);const cTo=new Date(pm.getFullYear(),pm.getMonth(),Math.min(d.getDate(),endMonth(pm).getDate()));return{from:startMonth(d),to:d,comparisonFrom:pm,comparisonTo:cTo,label:'Поточний місяць',comparisonLabel:'до такого ж періоду минулого місяця'}}if(period==='previous_month'){const pm=new Date(d.getFullYear(),d.getMonth()-1,1);const bm=new Date(d.getFullYear(),d.getMonth()-2,1);return{from:pm,to:endMonth(pm),comparisonFrom:bm,comparisonTo:endMonth(bm),label:'Минулий місяць',comparisonLabel:'до місяця перед ним'}}return{from:null,to:null,comparisonFrom:null,comparisonTo:null,label:'Весь період',comparisonLabel:'без порівняння'}}
export function inRange(date:string,from:Date|null,to:Date|null){if(!from||!to)return true;const d=parseDate(date);return d>=from&&d<=to}
export function aggregate(rows:DailyPoint[]){const revenue=rows.reduce((s,r)=>s+r.revenue,0);const orders=rows.reduce((s,r)=>s+r.orders,0);const markup=rows.reduce((s,r)=>s+r.markup,0);return{revenue,orders,markup,cost:revenue-markup,averageCheck:orders?revenue/orders:0,markupPercent:revenue?markup/revenue*100:0}}
export function change(current:number,previous:number){return previous?(current-previous)/previous*100:null}
