import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CalendarDays,CheckCircle2,Clock3,CupSoda,Lightbulb,ShoppingBasket,ShieldAlert,TrendingDown,TrendingUp,UtensilsCrossed} from 'lucide-react';
import {Payload,buildRange,change,inRange,money,num,pct} from '../sales/data';
import {cleanProductRows,normalizeProductName} from '../sales/semantic';
import {normalizeChannel} from '../sales/channelNames';
import {loadIntelligence,type IntelligencePayload} from '../sales/intelligence';
import {useFilters} from '../context/FilterContext';

type Priority='high'|'medium'|'low';
type Kind='risk'|'warning'|'opportunity'|'positive';
type Signal={id:string;title:string;detail:string;action:string;source:string;priority:Priority;kind:Kind;score:number;impact?:string;icon:any};
type Aggregate={revenue:number;orders:number;markup:number;averageCheck:number;markupPercent:number};
type ProductTrend={name:string;category:string;revenue:number;markup:number;quantity:number;previousRevenue:number;change:number|null};
type ChannelTrend={channel:string;revenue:number;markup:number;orders:number;previousRevenue:number;change:number|null;markupPercent:number};

const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const aggregate=(rows:any[]):Aggregate=>{const revenue=rows.reduce((sum,row)=>sum+(Number(row.revenue)||0),0),orders=rows.reduce((sum,row)=>sum+(Number(row.orders)||0),0),markup=rows.reduce((sum,row)=>sum+(Number(row.markup)||0),0);return{revenue,orders,markup,averageCheck:orders?revenue/orders:0,markupPercent:revenue?markup/revenue*100:0}};
const priorityLabel:Record<Priority,string>={high:'Високий',medium:'Середній',low:'Низький'};

export default function ExecutiveSignals(){
 const[sales,setSales]=useState<Payload|null>(null),[intelligence,setIntelligence]=useState<IntelligencePayload|null>(null),[loading,setLoading]=useState(true);
 const{filters}=useFilters();
 useEffect(()=>{let active=true;setLoading(true);Promise.all([fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'}).then(response=>response.json() as Promise<Payload>),loadIntelligence().catch(()=>null)]).then(([payload,intel])=>{if(!active)return;if(Number(payload.schemaVersion)!==2)throw Error('schemaVersion 2 required');setSales(payload);setIntelligence(intel)}).catch(error=>{console.error(error);if(active){setSales(null);setIntelligence(null)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const signals=useMemo<Signal[]>(()=>{
  const result:Signal[]=[];
  if(sales){
   const dateAllowed=(date:string)=>!filters.selectedDates.length||filters.selectedDates.includes(date);
   const currentRows=sales.daily.filter(row=>inRange(row.date,range.from,range.to)&&dateAllowed(row.date));
   const previousRows=filters.compareLFL&&filters.period!=='all'?sales.daily.filter(row=>inRange(row.date,range.comparisonFrom,range.comparisonTo)):[];
   const current=aggregate(currentRows),previous=aggregate(previousRows);
   if(filters.compareLFL&&previous.revenue>0){
    const revenueChange=change(current.revenue,previous.revenue),ordersChange=change(current.orders,previous.orders),checkChange=change(current.averageCheck,previous.averageCheck),markupChange=change(current.markup,previous.markup);
    if(revenueChange!==null&&revenueChange<=-10)result.push({id:'revenue-critical',title:'Критичне падіння обороту',detail:`Оборот нижчий на ${Math.abs(revenueChange).toFixed(1)}% до ${range.comparisonLabel.toLowerCase()}.`,action:'Розкласти падіння на чеки, середній чек і канали та призначити відповідального за відновлення.',source:'Продажі',priority:'high',kind:'risk',score:100+Math.abs(revenueChange),impact:money(previous.revenue-current.revenue),icon:TrendingDown});
    else if(revenueChange!==null&&revenueChange<0)result.push({id:'revenue-warning',title:'Оборот нижче попереднього періоду',detail:`Зниження становить ${Math.abs(revenueChange).toFixed(1)}%.`,action:'Перевірити канали та страви з найбільшим негативним внеском.',source:'Продажі',priority:'medium',kind:'warning',score:70+Math.abs(revenueChange),impact:money(previous.revenue-current.revenue),icon:TrendingDown});
    else if(revenueChange!==null&&revenueChange>=8)result.push({id:'revenue-growth',title:'Сильне зростання обороту',detail:`Оборот зріс на ${revenueChange.toFixed(1)}%.`,action:'Зафіксувати канали та позиції, які дали приріст, і масштабувати механіку.',source:'Продажі',priority:'medium',kind:'positive',score:50+revenueChange,impact:money(current.revenue-previous.revenue),icon:TrendingUp});
    if(ordersChange!==null&&ordersChange<-8)result.push({id:'orders-drop',title:'Падає кількість чеків',detail:`Чеків стало менше на ${Math.abs(ordersChange).toFixed(1)}%.`,action:'Перевірити трафік, доступність каналів, години роботи та відмови.',source:'Продажі',priority:ordersChange<=-15?'high':'medium',kind:'risk',score:88+Math.abs(ordersChange),icon:ShoppingBasket});
    if(checkChange!==null&&checkChange<-5)result.push({id:'check-drop',title:'Просідає середній чек',detail:`Середній чек знизився на ${Math.abs(checkChange).toFixed(1)}%.`,action:'Посилити допродажі, комбо та рекомендації напоїв до основних страв.',source:'Продажі',priority:'medium',kind:'warning',score:78+Math.abs(checkChange),impact:money(current.averageCheck),icon:ShoppingBasket});
    if(markupChange!==null&&revenueChange!==null&&markupChange<revenueChange-5)result.push({id:'markup-lag',title:'Націнка відстає від обороту',detail:`Оборот змінився на ${revenueChange.toFixed(1)}%, а націнка — на ${markupChange.toFixed(1)}%.`,action:'Перевірити структуру продажів, знижки та частку низькомаржинальних позицій.',source:'Маржинальність',priority:'high',kind:'risk',score:94+Math.abs(markupChange-revenueChange),icon:AlertTriangle});
   }
   const productMap=(from:Date|null,to:Date|null)=>{const map=new Map<string,{name:string;category:string;revenue:number;markup:number;quantity:number}>();cleanProductRows(sales.productsDaily.filter(row=>inRange(row.date,from,to)) as any).forEach((row:any)=>{const name=normalizeProductName(row.productName),key=name.toLowerCase(),category=String(row.category||'Без категорії').trim()||'Без категорії';const current=map.get(key)||{name,category,revenue:0,markup:0,quantity:0};current.revenue+=Number(row.revenue)||0;current.markup+=Number(row.markup)||0;current.quantity+=Number(row.quantity)||0;map.set(key,current)});return map};
   if(filters.compareLFL&&filters.period!=='all'){
    const currentProducts=productMap(range.from,range.to),previousProducts=productMap(range.comparisonFrom,range.comparisonTo);
    const trends:ProductTrend[]=[...currentProducts.values()].map(item=>{const previous=previousProducts.get(item.name.toLowerCase());return{...item,previousRevenue:previous?.revenue||0,change:change(item.revenue,previous?.revenue||0)}}).filter(item=>item.previousRevenue>=1000&&item.change!==null);
    const weakest=trends.filter(item=>item.change!<=-15).sort((a,b)=>a.change!-b.change!)[0];
    const strongest=trends.filter(item=>item.change!>=20).sort((a,b)=>b.change!-a.change!)[0];
    if(weakest)result.push({id:`product-${weakest.name}`,title:`Просідає страва: ${weakest.name}`,detail:`Оборот позиції впав на ${Math.abs(weakest.change!).toFixed(1)}%, поточний оборот — ${money(weakest.revenue)}.`,action:'Перевірити наявність, ціну, якість, фото, позицію в меню та рекомендацію персоналу.',source:`Страви · ${weakest.category}`,priority:weakest.change!<=-30?'high':'medium',kind:'risk',score:90+Math.abs(weakest.change!),impact:money(weakest.previousRevenue-weakest.revenue),icon:UtensilsCrossed});
    if(strongest)result.push({id:`product-growth-${strongest.name}`,title:`Росте страва: ${strongest.name}`,detail:`Оборот позиції зріс на ${strongest.change!.toFixed(1)}%.`,action:'Підсилити видимість, забезпечити стабільну наявність і перевірити потенціал комбо.',source:`Страви · ${strongest.category}`,priority:'low',kind:'opportunity',score:45+strongest.change!,impact:money(strongest.revenue-strongest.previousRevenue),icon:TrendingUp});
    const channelMap=(from:Date|null,to:Date|null)=>{const map=new Map<string,{channel:string;revenue:number;markup:number;orders:number}>();sales.channelsDaily.filter(row=>inRange(row.date,from,to)).forEach(row=>{const channel=normalizeChannel(row.channel),current=map.get(channel)||{channel,revenue:0,markup:0,orders:0};current.revenue+=Number(row.revenue)||0;current.markup+=Number(row.markup)||0;current.orders+=Number(row.orders)||0;map.set(channel,current)});return map};
    const currentChannels=channelMap(range.from,range.to),previousChannels=channelMap(range.comparisonFrom,range.comparisonTo);
    const channelTrends:ChannelTrend[]=[...currentChannels.values()].map(item=>{const previous=previousChannels.get(item.channel);return{...item,previousRevenue:previous?.revenue||0,change:change(item.revenue,previous?.revenue||0),markupPercent:item.revenue?item.markup/item.revenue*100:0}}).filter(item=>item.previousRevenue>0&&item.change!==null);
    const weakestChannel=channelTrends.filter(item=>item.change!<=-10).sort((a,b)=>a.change!-b.change!)[0];
    if(weakestChannel)result.push({id:`channel-${weakestChannel.channel}`,title:`Просідає канал: ${weakestChannel.channel}`,detail:`Оборот каналу впав на ${Math.abs(weakestChannel.change!).toFixed(1)}%, націнка — ${pct(weakestChannel.markupPercent)}.`,action:'Перевірити доступність меню, рейтинг, час приймання замовлень, промо та операційні відмови.',source:'Канали',priority:weakestChannel.change!<=-20?'high':'medium',kind:'risk',score:92+Math.abs(weakestChannel.change!),impact:money(weakestChannel.previousRevenue-weakestChannel.revenue),icon:ShieldAlert});
   }
  }
  const drinks=[...(intelligence?.drinkAttachment||[])].sort((a,b)=>a.attachmentRate-b.attachmentRate);
  const weakestDrink=drinks[0];
  if(weakestDrink){const target=weakestDrink.channel==='Зал'?60:weakestDrink.channel==='Самовивіз'?40:45,gap=weakestDrink.attachmentRate-target;if(gap<0)result.push({id:`drink-${weakestDrink.channel}`,title:`Низький Drink Attachment: ${weakestDrink.channel}`,detail:`Напій є у ${pct(weakestDrink.attachmentRate)} чеків при цілі ${pct(target)}. ${pct(weakestDrink.foodOnlyRate)} чеків містять тільки їжу.`,action:'Додати обов’язкову пропозицію напою, готові пари та контроль показника по зміні.',source:'Напої в чеках',priority:gap<=-15?'high':'medium',kind:'warning',score:85+Math.abs(gap),impact:`Розрив ${Math.abs(gap).toFixed(1)} п.п.`,icon:CupSoda});}
  const pair=[...(intelligence?.basketPairs||[])].filter(item=>item.coOccurrence>=5&&item.lift>1).sort((a,b)=>b.coOccurrence-a.coOccurrence||b.lift-a.lift)[0];
  if(pair)result.push({id:'best-pair',title:'Готова можливість для комбо',detail:`«${pair.itemA}» + «${pair.itemB}» зустрілись у ${num(pair.coOccurrence)} чеках, lift ${pair.lift.toFixed(2)}.`,action:'Протестувати комбо, рекомендацію в меню або скрипт персоналу.',source:'Кошик',priority:'low',kind:'opportunity',score:42+Math.min(pair.coOccurrence,30),impact:`${num(pair.coOccurrence)} чеків`,icon:Lightbulb});
  const heat=intelligence?.heatmap||[],peak=[...heat].sort((a,b)=>b.orders-a.orders)[0],weak=[...heat].filter(item=>item.orders>0).sort((a,b)=>a.orders-b.orders)[0];
  if(peak)result.push({id:'peak-slot',title:'Пік операційного навантаження',detail:`${peak.weekday}, ${peak.hour}:00 — ${num(peak.orders)} чеків у вибірці.`,action:'Підсилити готовність кухні, заготівлі й склад зміни перед цим слотом.',source:'Операції',priority:'medium',kind:'warning',score:68+Math.min(peak.orders,25),impact:money(peak.revenue),icon:Clock3});
  if(weak)result.push({id:'weak-slot',title:'Слабкий операційний слот',detail:`${weak.weekday}, ${weak.hour}:00 — лише ${num(weak.orders)} чеків.`,action:'Перевірити локальну активацію, спеціальну пропозицію або оптимізацію ресурсу без масової знижки.',source:'Операції',priority:'low',kind:'opportunity',score:38,icon:CalendarDays});
  const risk=(intelligence?.customerProfiles||[]).filter(item=>item.segment==='У ризику'||item.segment==='Сплячі');
  if(risk.length)result.push({id:'customer-risk',title:'Клієнти потребують реактивації',detail:`У сегментах «У ризику» та «Сплячі» — ${num(risk.length)} клієнтів.`,action:'Створити окрему персональну реактиваційну комунікацію та не розсилати її всій базі.',source:'Клієнти',priority:risk.length>=50?'high':'medium',kind:'warning',score:74+Math.min(risk.length/5,20),impact:`${num(risk.length)} клієнтів`,icon:ShieldAlert});
  if(!result.some(signal=>signal.kind==='risk'||signal.kind==='warning'))result.push({id:'stable',title:'Критичних відхилень не виявлено',detail:'Основні контрольовані показники не сформували сигналів високого ризику.',action:'Продовжувати моніторинг і сфокусуватися на можливостях росту.',source:'Система',priority:'low',kind:'positive',score:20,icon:CheckCircle2});
  return result.sort((a,b)=>b.score-a.score);
 },[sales,intelligence,range,filters.selectedDates,filters.compareLFL,filters.period]);
 const counts=useMemo(()=>({high:signals.filter(signal=>signal.priority==='high').length,medium:signals.filter(signal=>signal.priority==='medium').length,opportunity:signals.filter(signal=>signal.kind==='opportunity'||signal.kind==='positive').length}),[signals]);
 if(loading)return <section className="mx-auto mb-6 max-w-[1600px] px-4 md:px-8"><div className="rounded-[28px] border border-white/10 bg-white/[.055] p-7 text-sm text-white/45">Формуємо управлінські сигнали…</div></section>;
 return <section className="mx-auto mb-6 max-w-[1600px] px-4 md:px-8"><div className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-white/35">MANAGEMENT ACTION CENTER</p><h2 className="mt-2 text-3xl font-black text-[#d8f4f2]">Управлінські сигнали</h2><p className="mt-1 text-sm text-white/50">Автоматичне ранжування ризиків, відхилень і можливостей за поточними фільтрами.</p></div><div className="flex flex-wrap gap-2"><Badge label="Високий" value={counts.high} tone="risk"/><Badge label="Середній" value={counts.medium} tone="warning"/><Badge label="Можливості" value={counts.opportunity} tone="positive"/></div></div><div className="grid gap-4 lg:grid-cols-2">{signals.slice(0,10).map(signal=><SignalCard key={signal.id} signal={signal}/>)}</div>{signals.length>10&&<p className="mt-4 text-xs text-white/35">Показано 10 із {signals.length} сигналів із найвищим пріоритетом.</p>}</div></section>;
}

function Badge({label,value,tone}:{label:string;value:number;tone:'risk'|'warning'|'positive'}){return <div className={`rounded-xl border px-3 py-2 text-xs font-black ${tone==='risk'?'border-rose-300/20 bg-rose-300/10 text-rose-100':tone==='warning'?'border-amber-300/20 bg-amber-300/10 text-amber-100':'border-emerald-300/20 bg-emerald-300/10 text-emerald-100'}`}>{label}: {num(value)}</div>}
function SignalCard({signal}:{signal:Signal}){const Icon=signal.icon;const style=signal.kind==='risk'?'border-rose-300/25 bg-rose-300/[.08]':signal.kind==='warning'?'border-amber-300/20 bg-amber-300/[.07]':signal.kind==='opportunity'?'border-sky-300/20 bg-sky-300/[.07]':'border-emerald-300/20 bg-emerald-300/[.07]';return <article className={`rounded-2xl border p-5 ${style}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-black/15"><Icon size={20}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${signal.priority==='high'?'bg-rose-300/15 text-rose-100':signal.priority==='medium'?'bg-amber-300/15 text-amber-100':'bg-white/[.07] text-white/55'}`}>{priorityLabel[signal.priority]} пріоритет</span><span className="text-[10px] font-black uppercase tracking-[.14em] text-white/35">{signal.source}</span></div><h3 className="mt-3 text-lg font-black">{signal.title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{signal.detail}</p>{signal.impact&&<p className="mt-2 text-xs font-black text-white/45">Оцінка впливу: <span className="text-[#cfeeed]">{signal.impact}</span></p>}<div className="mt-4 rounded-xl border border-white/8 bg-black/10 p-3"><p className="text-[10px] font-black uppercase tracking-[.14em] text-white/35">Рекомендована дія</p><p className="mt-1 text-sm font-bold text-[#cfeeed]">{signal.action}</p></div></div></div></article>}
