import { useEffect, useState } from 'react';
import {BarChart3,BrainCircuit,CalendarDays,Clock3,Layers3,Menu,MessageSquareText,Radio,ShieldCheck,UtensilsCrossed,X} from 'lucide-react';

type IntelligenceRoute='dashboard'|'dashboard_reviews'|'dashboard_sales'|'dashboard_menu'|'dashboard_channels'|'dashboard_executive'|'dashboard_daypart'|'dashboard_weekday'|'dashboard_categories';
const routeHref=(route:IntelligenceRoute)=>`?view=${route}`;
const items=[
 {key:'dashboard_executive' as const,label:'Головна',icon:BrainCircuit},
 {key:'dashboard_sales' as const,label:'Продажі',icon:BarChart3},
 {key:'dashboard_menu' as const,label:'Страви',icon:UtensilsCrossed},
 {key:'dashboard_categories' as const,label:'Категорії',icon:Layers3},
 {key:'dashboard_channels' as const,label:'Канали',icon:Radio},
 {key:'dashboard_daypart' as const,label:'Години',icon:Clock3},
 {key:'dashboard_weekday' as const,label:'Дні тижня',icon:CalendarDays},
 {key:'dashboard' as const,label:'Feedback BI',icon:MessageSquareText},
 {key:'dashboard_reviews' as const,label:'Керування відгуками',icon:ShieldCheck},
];
export default function IntelligenceNav({active}:{active:IntelligenceRoute}){const[open,setOpen]=useState(false);const activeItem=items.find(i=>i.key===active)??items[0];useEffect(()=>setOpen(false),[active]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);return <><header className="sticky top-0 z-[110] border-b border-white/10 bg-[#4c061c]/95 px-3 text-white shadow-[0_10px_28px_rgba(31,0,11,.24)] backdrop-blur-xl md:px-6"><div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between gap-3"><a href={routeHref('dashboard_executive')} className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-[#cfeeed] text-sm font-black text-[#531027]">M</div><div className="min-w-0"><div className="truncate text-sm font-black tracking-tight text-[#d8f4f2] sm:text-base">MARMOO · Аналітичний центр</div><div className="truncate text-[10px] font-bold uppercase tracking-[.16em] text-white/40">{activeItem.label}</div></div></a><button type="button" onClick={()=>setOpen(v=>!v)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 bg-white/[.05] text-[#d8f4f2]">{open?<X size={20}/>:<Menu size={20}/>}</button></div></header>{open&&<div className="fixed inset-0 z-[105] bg-black/45 backdrop-blur-sm" onClick={()=>setOpen(false)}><nav onClick={e=>e.stopPropagation()} className="absolute right-3 top-[72px] w-[min(92vw,360px)] rounded-3xl border border-white/12 bg-[#3f0417]/98 p-3 text-white shadow-2xl md:right-6"><div className="mb-2 px-3 py-2 text-[10px] font-black uppercase tracking-[.2em] text-[#cfeeed]/50">Розділи аналітики</div><div className="grid gap-1.5">{items.map(({key,label,icon:Icon})=>{const selected=active===key;return <a key={key} href={routeHref(key)} className={`flex items-center justify-between rounded-2xl border px-4 py-3.5 text-sm font-black transition ${selected?'border-[#cfeeed] bg-[#cfeeed] text-[#531027]':'border-transparent bg-white/[.035] text-white/70 hover:bg-white/[.08] hover:text-white'}`}><span className="flex items-center gap-3"><Icon size={17}/>{label}</span>{selected&&<span className="rounded-full bg-[#531027]/10 px-2 py-1 text-[9px] uppercase tracking-[.12em]">Відкрито</span>}</a>})}</div></nav></div>}</>}
