import {useEffect,useMemo,useState} from 'react';
import {Layers3,RefreshCw,TrendingUp,Utensils,WalletCards} from 'lucide-react';
import {Payload,PERIODS,PeriodKey,buildRange,inRange,money,num,pct,fullDate,shortDate} from './sales/data';
import {cleanProductRows,normalizeProductName} from './sales/semantic';

type CategoryRow={category:string;quantity:number;revenue:number;markup:number;avgPrice:number;markupPercent:number;share:number;items:number;leader:string;leaderRevenue:number};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;

export default function CategoryDashboard(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<PeriodKey>('current_month');
 const load=async()=>{setLoading(true);try{const r=await fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json() as Payload;if(Number(p.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(period,new Date()),[period]);
 const rows=useMemo<CategoryRow[]>(()=>{if(!data)return[];const source=cleanProductRows(data.productsDaily.filter(x=>inRange(x.date,range.from,range.to)) as any);const cats=new Map<string,any>();
 source.forEach((x:any)=>{const category=String(x.category||'Без категорії').trim()||'Без категорії';const name=normalizeProductName(x.productName);const cur=cats.get(category)||{category,quantity:0,revenue:0,markup:0,products:new Map<string,number>()};cur.quantity+=Number(x.quantity)||0;cur.revenue+=Number(x.revenue)||0;cur.markup+=Number(x.markup)||0;cur.products.set(name,(cur.products.get(name)||0)+(Number(x.revenue)||0));cats.set(category,cur)});
 const total=[...cats.values()].reduce((s,x)=>s+x.revenue,0);return[...cats.values()].map(x=>{const leader=[...x.products.entries()].sort((a:any,b:any)=>b[1]-a[1])[0]||['—',0];return{category:x.category,quantity:x.quantity,revenue:x.revenue,markup:x.markup,avgPrice:x.quantity?x.revenue/x.quantity:0,markupPercent:x.revenue?x.markup/x.revenue*100:0,share:total?x.revenue/total*100:0,items:x.products.size,leader:String(leader[0]),leaderRevenue:Number(leader[1])}}).sort((a,b)=>b.revenue-a.revenue)},[data,range]);
 const totals=rows.reduce((a,x)=>({revenue:a.revenue+x.revenue,quantity:a.quantity+x.quantity,markup:a.markup+x.markup}),{revenue:0,quantity:0,markup:0});
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8">
 <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">MARMOO Intelligence</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Category Intelligence</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити</button></header>
 <div className="mb-6 overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{PERIODS.map(p=><button key={p.key} onClick={()=>setPeriod(p.key)} className={`rounded-xl border px-4 py-2.5 text-sm font-bold ${period===p.key?'border-[#cfeeed] bg-[#cfeeed] text-[#5b0b25]':'border-white/10 bg-white/[.05] text-white/65'}`}>{p.label}</button>)}</div></div>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label="Оборот" value={money(totals.revenue)}/><Kpi icon={Utensils} label="Продано" value={`${num(totals.quantity)} од.`}/><Kpi icon={TrendingUp} label="Націнка" value={money(totals.markup)} sub={pct(totals.revenue?totals.markup/totals.revenue*100:0)}/><Kpi icon={Layers3} label="Категорій" value={num(rows.length)}/></div>
 <section className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">Ефективність категорій</h2><p className="mt-1 text-sm text-white/50">Оборот, структура, націнка та головна страва кожної категорії</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Категорія</th><th className="text-right">Частка</th><th className="text-right">Оборот</th><th className="text-right">Кількість</th><th className="text-right">Сер. ціна</th><th className="text-right">Націнка</th><th className="text-right">Націнка %</th><th className="text-right">Позицій</th><th>Лідер категорії</th></tr></thead><tbody>{rows.map((x,i)=><tr key={x.category} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-bold">{x.category}</td><td className="text-right">{pct(x.share)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right">{money(x.avgPrice)}</td><td className="text-right">{money(x.markup)}</td><td className="text-right">{pct(x.markupPercent)}</td><td className="text-right">{num(x.items)}</td><td><b>{x.leader}</b><div className="text-xs text-white/40">{money(x.leaderRevenue)}</div></td></tr>)}</tbody></table></div></section>
 </div></div>
}

function Kpi({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div>{sub&&<div className="mt-1 text-xs font-bold text-[#cfeeed]/70">{sub}</div>}</div>}
