import {useEffect,useMemo,useState} from 'react';
import {CupSoda,RefreshCw,Radio,TrendingUp,ReceiptText,WalletCards} from 'lucide-react';
import {Payload,buildRange,inRange,money,num,pct,fullDate,shortDate} from './sales/data';
import {loadIntelligence,type IntelligencePayload} from './sales/intelligence';
import {normalizeChannel} from './sales/channelNames';
import {useFilters} from './context/FilterContext';

type ChannelRow={channel:string;revenue:number;orders:number;markup:number;averageCheck:number;markupPercent:number;share:number};
type DrinkRow={channel:string;orders:number;ordersWithDrink:number;foodOnlyOrders:number;revenue:number;attachmentRate:number;foodOnlyRate:number};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;

export default function ChannelDashboard(){
 const[data,setData]=useState<Payload|null>(null),[intelligence,setIntelligence]=useState<IntelligencePayload|null>(null),[loading,setLoading]=useState(true);
 const{filters,toggleChannel}=useFilters();
 const load=async()=>{setLoading(true);try{const[sales,intel]=await Promise.all([fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.json() as Promise<Payload>),loadIntelligence().catch(()=>null)]);if(Number(sales.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(sales);setIntelligence(intel)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const rows=useMemo<ChannelRow[]>(()=>{if(!data)return[];const map=new Map<string,ChannelRow>();data.channelsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const key=normalizeChannel(x.channel);if(filters.selectedChannels.length&&!filters.selectedChannels.includes(key))return;const cur=map.get(key)||{channel:key,revenue:0,orders:0,markup:0,averageCheck:0,markupPercent:0,share:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;cur.markup+=Number(x.markup)||0;map.set(key,cur)});const total=[...map.values()].reduce((s,x)=>s+x.revenue,0);return[...map.values()].map(x=>({...x,averageCheck:x.orders?x.revenue/x.orders:0,markupPercent:x.revenue?x.markup/x.revenue*100:0,share:total?x.revenue/total*100:0})).sort((a,b)=>b.revenue-a.revenue)},[data,range,filters.selectedChannels]);
 const totals=useMemo(()=>rows.reduce((a,x)=>({revenue:a.revenue+x.revenue,orders:a.orders+x.orders,markup:a.markup+x.markup}),{revenue:0,orders:0,markup:0}),[rows]);
 const drinks=useMemo<DrinkRow[]>(()=>{const map=new Map<string,DrinkRow>();for(const x of intelligence?.drinkAttachment||[]){const channel=normalizeChannel(x.channel);if(filters.selectedChannels.length&&!filters.selectedChannels.includes(channel))continue;const cur=map.get(channel)||{channel,orders:0,ordersWithDrink:0,foodOnlyOrders:0,revenue:0,attachmentRate:0,foodOnlyRate:0};cur.orders+=Number(x.orders)||0;cur.ordersWithDrink+=Number(x.ordersWithDrink)||0;cur.foodOnlyOrders+=Number(x.foodOnlyOrders)||0;cur.revenue+=Number(x.revenue)||0;map.set(channel,cur)}return[...map.values()].map(x=>({...x,attachmentRate:x.orders?x.ordersWithDrink/x.orders*100:0,foodOnlyRate:x.orders?x.foodOnlyOrders/x.orders*100:0})).sort((a,b)=>b.orders-a.orders)},[intelligence,filters.selectedChannels]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8">
  <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">АНАЛІТИКА ПРОДАЖІВ</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Канали продажів</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
  <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label="Оборот" value={money(totals.revenue)}/><Kpi icon={ReceiptText} label="Чеки" value={num(totals.orders)}/><Kpi icon={TrendingUp} label="Середній чек" value={money(totals.orders?totals.revenue/totals.orders:0)}/><Kpi icon={Radio} label="Націнка" value={money(totals.markup)} sub={pct(totals.revenue?totals.markup/totals.revenue*100:0)}/></div>
  <section className="mb-6 rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">Ефективність каналів</h2><p className="mt-1 text-sm text-white/50">Натисни на канал, щоб застосувати або зняти глобальний фільтр</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Канал</th><th className="text-right">Частка</th><th className="text-right">Оборот</th><th className="text-right">Чеки</th><th className="text-right">Середній чек</th><th className="text-right">Націнка</th><th className="text-right">Націнка %</th></tr></thead><tbody>{rows.map((x,i)=><tr key={x.channel} onClick={()=>toggleChannel(x.channel)} className="cursor-pointer border-b border-white/[.07] transition hover:bg-white/[.05]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-bold">{x.channel}</td><td className="text-right">{pct(x.share)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{num(x.orders)}</td><td className="text-right">{money(x.averageCheck)}</td><td className="text-right">{money(x.markup)}</td><td className="text-right">{pct(x.markupPercent)}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-5 flex items-start gap-3"><CupSoda className="mt-1 text-[#cfeeed]"/><div><h2 className="text-2xl font-black text-[#d8f4f2]">Напої в чеках</h2><p className="mt-1 text-sm text-white/50">Drink Attachment Rate за весь доступний чековий період · COST не враховується</p></div></div>{drinks.length?<div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">Канал</th><th className="text-right">Чеки</th><th className="text-right">З напоями</th><th className="text-right">Attachment Rate</th><th className="text-right">Тільки їжа</th><th>Статус</th></tr></thead><tbody>{drinks.map(x=>{const target=x.channel==='Зал'?60:x.channel==='Самовивіз'?40:45;const gap=x.attachmentRate-target;return <tr key={x.channel} className="border-b border-white/[.07]"><td className="py-4 font-bold">{x.channel}</td><td className="text-right">{num(x.orders)}</td><td className="text-right">{num(x.ordersWithDrink)}</td><td className="text-right font-black text-[#cfeeed]">{pct(x.attachmentRate)}</td><td className="text-right">{pct(x.foodOnlyRate)}</td><td><span className={`rounded-full px-3 py-1 text-xs font-black ${gap>=0?'bg-emerald-300/15 text-emerald-200':gap>-10?'bg-amber-300/15 text-amber-200':'bg-rose-300/15 text-rose-200'}`}>{gap>=0?'Норма':`Розрив ${gap.toFixed(1)} п.п.`}</span></td></tr>})}</tbody></table></div>:<p className="text-sm text-white/45">Новий чековий snapshot ще не згенерований. Після deployment блок заповниться автоматично.</p>}</section>
 </div></div>
}

function Kpi({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div>{sub&&<div className="mt-1 text-xs font-bold text-[#cfeeed]/70">{sub}</div>}</div>}
