import {useEffect,useMemo,useState} from 'react';
import {Clock3,RefreshCw,TrendingUp,ReceiptText,WalletCards} from 'lucide-react';
import {Payload,buildRange,inRange,money,num,pct,fullDate,shortDate} from './sales/data';
import {loadIntelligence,type IntelligencePayload} from './sales/intelligence';
import {useFilters} from './context/FilterContext';
import OperationsHeatmap from './components/OperationsHeatmap';

type Row={hour:number;revenue:number;orders:number;markup:number;averageCheck:number;markupPercent:number;share:number};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const part=(h:number)=>h<12?'Ранок':h<17?'Обід':h<21?'Вечір':'Пізній вечір';

export default function DaypartDashboard(){
 const[data,setData]=useState<Payload|null>(null),[intelligence,setIntelligence]=useState<IntelligencePayload|null>(null),[loading,setLoading]=useState(true);
 const{filters}=useFilters();
 const load=async()=>{setLoading(true);try{const[sales,intel]=await Promise.all([fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.json() as Promise<Payload>),loadIntelligence().catch(()=>null)]);if(Number(sales.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(sales);setIntelligence(intel)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const rows=useMemo<Row[]>(()=>{if(!data)return[];const map=new Map<number,Row>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)&&x.hour>=10&&x.hour<=22).forEach(x=>{const cur=map.get(x.hour)||{hour:x.hour,revenue:0,orders:0,markup:0,averageCheck:0,markupPercent:0,share:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;cur.markup+=Number(x.markup)||0;map.set(x.hour,cur)});const total=[...map.values()].reduce((s,x)=>s+x.revenue,0);return[...map.values()].map(x=>({...x,averageCheck:x.orders?x.revenue/x.orders:0,markupPercent:x.revenue?x.markup/x.revenue*100:0,share:total?x.revenue/total*100:0})).sort((a,b)=>a.hour-b.hour)},[data,range]);
 const totalRevenue=rows.reduce((s,x)=>s+x.revenue,0),totalOrders=rows.reduce((s,x)=>s+x.orders,0),peak=[...rows].sort((a,b)=>b.revenue-a.revenue)[0],weak=[...rows].filter(x=>x.orders>0).sort((a,b)=>a.revenue-b.revenue)[0];
 const parts=useMemo(()=>{const m=new Map<string,{label:string;revenue:number;orders:number;markup:number}>();rows.forEach(x=>{const k=part(x.hour),c=m.get(k)||{label:k,revenue:0,orders:0,markup:0};c.revenue+=x.revenue;c.orders+=x.orders;c.markup+=x.markup;m.set(k,c)});return[...m.values()]},[rows]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8">
 <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">ОПЕРАЦІЙНА АНАЛІТИКА</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Продажі за годинами</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label="Оборот" value={money(totalRevenue)}/><Kpi icon={ReceiptText} label="Чеки" value={num(totalOrders)}/><Kpi icon={TrendingUp} label="Пікова година" value={peak?`${peak.hour}:00`:'—'} sub={peak?money(peak.revenue):undefined}/><Kpi icon={Clock3} label="Найслабша година" value={weak?`${weak.hour}:00`:'—'} sub={weak?money(weak.revenue):undefined}/></div>
 <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{parts.map(x=><div key={x.label} className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-black uppercase text-white/45">{x.label}</p><div className="mt-2 text-2xl font-black text-[#d8f4f2]">{money(x.revenue)}</div><div className="mt-2 text-xs text-white/50">{num(x.orders)} чеків · {money(x.orders?x.revenue/x.orders:0)} середній чек</div></div>)}</div>
 {intelligence?.heatmap?.length?<div className="mb-6"><OperationsHeatmap cells={intelligence.heatmap} metric="orders" title="Завантаження кухні: день × година"/></div>:null}
 <section className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">Ефективність по годинах</h2><p className="mt-1 text-sm text-white/50">Робочі години MARMOO: 10:00–22:00</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">Година</th><th>Частина дня</th><th className="text-right">Частка</th><th className="text-right">Оборот</th><th className="text-right">Чеки</th><th className="text-right">Середній чек</th><th className="text-right">Націнка</th><th className="text-right">Націнка %</th></tr></thead><tbody>{rows.map(x=><tr key={x.hour} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{x.hour}:00</td><td>{part(x.hour)}</td><td className="text-right">{pct(x.share)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{num(x.orders)}</td><td className="text-right">{money(x.averageCheck)}</td><td className="text-right">{money(x.markup)}</td><td className="text-right">{pct(x.markupPercent)}</td></tr>)}</tbody></table></div></section>
 </div></div>;
}
function Kpi({icon:Icon,label,value,sub}:{icon:any;label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div>{sub&&<div className="mt-1 text-xs font-bold text-[#cfeeed]/70">{sub}</div>}</div>}
