import React,{useEffect,useMemo,useState,type ReactNode}from'react';
import{BarChart3,Gauge,Heart,MessageSquareText,RefreshCw,Star,Target,Users,UtensilsCrossed,X}from'lucide-react';
import{Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,PolarAngleAxis,PolarGrid,Radar,RadarChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{buildRange,inRange,fullDate}from'./sales/data';
import{useFilters}from'./context/FilterContext';

type Row=Record<string,unknown>;
type Metric='responses'|'nps'|'experience'|'service'|'taste'|'return';
type Grain='day'|'week'|'month';
type Theme={key:string;label:string;count:number;samples:string[];tone:'positive'|'negative';priority:number};
type ThemeRule={key:string;label:string;words:string[]};
type ThemeAccumulator={count:number;samples:string[];critical:number};

const API_URL=import.meta.env.VITE_API_URL||`${import.meta.env.BASE_URL||'/'}data.json`;
const C={cyan:'#CFF3F2',cyan2:'#8DE0DE',gold:'#F3C969',rose:'#F08AA5',muted:'#CBB5BD',grid:'#7D3046'};
const A={id:['ID','Response ID'],date:['Timestamp','Date'],total:['Total Score (q1)','Q1_General'],ambience:['Ambience Rating (q2)','Q2_Atmosphere_Rating'],ambienceText:['Ambience Matches (q3)','Q3_Atmosphere_Likes'],hall:['Hall Improvements (q4)','Q4_Atmosphere_Improvements'],service:['Service Rating (q5)','Q5_Service_Rating'],staff:['Staff Comfort (q6)','Q6_Service_Comfort'],serviceText:['Service Improvements (q7)','Q7_Service_Improvements'],taste:['Food Taste (q8)','Q8_Food_Taste'],presentation:['Food Presentation (q9)','Q9_Food_Presentation'],comfort:['Stay Comfort (q12)','Q12_Comfort_Rating'],discomfort:['Stay Discomfort (q13)','Q13_Comfort_Dislikes'],critical:['CRITICAL FIX (q14)','Q14_Priority_Fix'],ret:['Will Return (q15)','Q15_Return_Intent'],nps:['NPS Score (q16)','Q16_NPS'],comment:['User Comment (q17)','Q17_Comments'],gender:['Gender'],age:['Age Group','AgeGroup'],dishId:['Response ID','ID'],dishName:['Dish Name'],dishRating:['Dish Rating'],dishComment:['Dish Comment']}as const;

const NEG:ThemeRule[]=[
 {key:'menu',label:'Меню / асортимент',words:['меню','позиці','вибір','асортимент','дитяч']},
 {key:'bar',label:'Бар / алкоголь',words:['алког','пиво','коктейл','бар']},
 {key:'speed',label:'Швидкість видачі',words:['швидк','очікуван','довго','винесен','приготуван']},
 {key:'service',label:'Уважність / сервіс',words:['уважн','офіціант','персонал','розрахунк','непорозум']},
 {key:'climate',label:'Температура / клімат',words:['температур','прохолод','холод','жарко']},
 {key:'hall',label:'Столи / ергономіка',words:['столи','стільчик','близько','прохід']},
 {key:'access',label:'Доступність / родини',words:['доступн','маломоб','підгуз','дитин','малюк','куточок']},
 {key:'ops',label:'Операційні дрібниці',words:['сервет','зубочист','спеці','вода','антисеп','урна','смітник']},
 {key:'taste',label:'Смак / рецептура',words:['соус','прожарк','м’яс',"м'яс",'смак','теплим','стейк не стейк']},
 {key:'light',label:'Світло / музика',words:['освітлен','світло','музик','гучн']}
];
const POS:ThemeRule[]=[
 {key:'staff',label:'Привітність персоналу',words:['привітн','офіціант','персонал','команда','адміністратор']},
 {key:'interior',label:'Інтер’єр',words:['інтер’єр',"інтер'єр",'декор']},
 {key:'clean',label:'Чистота',words:['чистот']},
 {key:'music',label:'Музика',words:['музик','гучн']},
 {key:'light',label:'Освітлення',words:['освітлен','світло']},
 {key:'food',label:'Смак страв',words:['смач','смак','неперевершен']},
 {key:'value',label:'Ціна / цінність',words:['дуже вигідно','ціна повністю виправдана']},
 {key:'overall',label:'Усе сподобалось',words:['усе сподобалось','все супер','все чудово','бездоган']}
];

const pick=(row:Row,keys:readonly string[])=>{for(const key of keys){const value=row[key];if(value!==undefined&&value!==null&&value!=='')return value}return null};
const text=(row:Row,keys:readonly string[])=>String(pick(row,keys)??'').trim();
const number=(row:Row,keys:readonly string[])=>{const raw=pick(row,keys);if(raw===null)return null;const value=Number(String(raw).replace(',','.'));return Number.isFinite(value)?value:null};
const parseDate=(value:unknown)=>{const raw=String(value??'').trim();const match=raw.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})/);if(match)return`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`;const date=new Date(raw);return Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10)};
const avg=(values:(number|null)[])=>{const clean=values.filter((value):value is number=>value!==null&&Number.isFinite(value));return clean.length?clean.reduce((sum,value)=>sum+value,0)/clean.length:null};
const norm=(value:string)=>value.toLowerCase().replace(/[’ʼ]/g,"'").replace(/\s+/g,' ').trim();
const format=(value:number|null,digits=1)=>value===null||!Number.isFinite(value)?'—':new Intl.NumberFormat('uk-UA',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value);
const calcNps=(rows:Row[])=>{let promoters=0,passives=0,detractors=0;rows.forEach(row=>{const value=number(row,A.nps);if(value===null)return;if(value>=9)promoters++;else if(value<=6)detractors++;else passives++});const total=promoters+passives+detractors;return{score:total?Math.round((promoters-detractors)/total*100):null,promoters,passives,detractors}};
const experience=(rows:Row[])=>{const values=rows.map(row=>avg([number(row,A.total)!==null?number(row,A.total)!/10:null,...[A.ambience,A.service,A.taste,A.presentation,A.comfort].map(keys=>number(row,keys)!==null?number(row,keys)!/5:null)])).filter((value):value is number=>value!==null);const result=avg(values);return result===null?null:result*100};
const returnRate=(rows:Row[],strong=true)=>{const values=rows.map(row=>text(row,A.ret).toLowerCase()).filter(Boolean);if(!values.length)return null;const matched=values.filter(value=>strong?value.includes('обов'):value.includes('обов')||value.includes('скоріш')).length;return matched/values.length*100};
const metrics=(rows:Row[])=>({responses:rows.length,nps:calcNps(rows).score,experience:experience(rows),total:avg(rows.map(row=>number(row,A.total))),ambience:avg(rows.map(row=>number(row,A.ambience))),service:avg(rows.map(row=>number(row,A.service))),taste:avg(rows.map(row=>number(row,A.taste))),presentation:avg(rows.map(row=>number(row,A.presentation))),comfort:avg(rows.map(row=>number(row,A.comfort))),return:returnRate(rows),positive:returnRate(rows,false)});

function buildThemes(rows:Row[],dishes:Row[],tone:'positive'|'negative'):Theme[]{
 const rules:ThemeRule[]=tone==='positive'?POS:NEG;
 const map=new Map<string,ThemeAccumulator>();
 const addMatch=(rule:ThemeRule,source:string,critical=false)=>{const current=map.get(rule.key)??{count:0,samples:[],critical:0};current.count+=1;if(source&&!current.samples.includes(source)&&current.samples.length<5)current.samples.push(source);if(critical)current.critical+=1;map.set(rule.key,current)};
 rows.forEach(row=>{const source=(tone==='positive'?[text(row,A.ambienceText),text(row,A.staff),text(row,A.comment)]:[text(row,A.hall),text(row,A.serviceText),text(row,A.discomfort),text(row,A.critical)]).filter(Boolean).join(' • ');const normalized=norm(source);if(!normalized)return;rules.forEach(rule=>{if(rule.words.some(word=>normalized.includes(norm(word))))addMatch(rule,source,tone==='negative'&&Boolean(text(row,A.critical)))})});
 if(tone==='negative')dishes.forEach(row=>{const source=text(row,A.dishComment),normalized=norm(source);if(!normalized)return;rules.forEach(rule=>{if(rule.words.some(word=>normalized.includes(norm(word))))addMatch(rule,source)})});
 return rules.map<Theme>(rule=>{const current:ThemeAccumulator=map.get(rule.key)??{count:0,samples:[],critical:0};return{key:rule.key,label:rule.label,count:current.count,samples:current.samples,tone,priority:current.count*10+current.critical*6}}).filter(theme=>theme.count>0).sort((a,b)=>b.priority-a.priority);
}

const dishCats=(raw:string)=>{const value=norm(raw),out:string[]=[];const add=(name:string)=>{if(!out.includes(name))out.push(name)};if(value.includes('стейк')&&value.includes('боул'))add('Стейк-боул');if(value.includes('бургер'))add('Бургер');if(value.includes('тако'))add('Тако');if(value.includes('мелт'))add('Мелт');if(value.includes('удон'))add('Удон');if(value.includes('суп')||value.includes('колаген'))add('Колагеновий суп');if(value.includes('салат'))add('Салат');if(value.includes('боул')&&!out.includes('Стейк-боул'))add('Боул');if(value.includes('стейк')&&!out.includes('Стейк-боул'))add('Стейк');if(!out.length&&raw&&value!=='кайф')add(raw.length>34?`${raw.slice(0,34)}…`:raw);return out};
const tooltipStyle={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};

export default function FeedbackDashboardGlobal(){
 const[data,setData]=useState<{general:Row[];dishes:Row[]}>({general:[],dishes:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[metric,setMetric]=useState<Metric>('experience'),[grain,setGrain]=useState<Grain>('day'),[theme,setTheme]=useState<Theme|null>(null),[npsFilter,setNpsFilter]=useState<'all'|'promoter'|'passive'|'detractor'>('all'),[tab,setTab]=useState<'general'|'dishes'>('general'),[page,setPage]=useState(0);
 const{filters}=useFilters();
 const load=async()=>{setLoading(true);setError('');try{const response=await fetch(`${API_URL}${API_URL.includes('?')?'&':'?'}_=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const json=await response.json();setData({general:Array.isArray(json.general)?json.general:[],dishes:Array.isArray(json.dishes)?json.dishes:[]})}catch(err){console.error(err);setError('Не вдалося завантажити General і Dishes.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const latest=useMemo(()=>data.general.map(row=>parseDate(pick(row,A.date))).filter(Boolean).sort().at(-1)||'',[data.general]);
 const range=useMemo(()=>buildRange(filters.period,latest?new Date(`${latest}T00:00:00`):new Date()),[filters.period,latest]);
 const rows=useMemo(()=>data.general.filter(row=>{const date=parseDate(pick(row,A.date));if(date&&!inRange(date,range.from,range.to))return false;const query=filters.searchQuery.trim().toLowerCase();if(query&&!Object.values(row).some(value=>String(value??'').toLowerCase().includes(query)))return false;const score=number(row,A.nps);if(npsFilter==='promoter'&&(score===null||score<9))return false;if(npsFilter==='passive'&&(score===null||score<7||score>8))return false;if(npsFilter==='detractor'&&(score===null||score>6))return false;return true}),[data.general,range,filters.searchQuery,npsFilter]);
 const previousRows=useMemo(()=>data.general.filter(row=>{const date=parseDate(pick(row,A.date));return date?inRange(date,range.comparisonFrom,range.comparisonTo):false}),[data.general,range]);
 const ids=useMemo(()=>new Set(rows.map(row=>text(row,A.id)).filter(Boolean)),[rows]);
 const dishes=useMemo(()=>data.dishes.filter(row=>ids.has(text(row,A.dishId))||inRange(parseDate(pick(row,A.date)),range.from,range.to)),[data.dishes,ids,range]);
 const current=useMemo(()=>metrics(rows),[rows]),previous=useMemo(()=>metrics(previousRows),[previousRows]),npsData=useMemo(()=>calcNps(rows),[rows]);
 const trend=useMemo(()=>{const map=new Map<string,Row[]>();rows.forEach(row=>{const raw=parseDate(pick(row,A.date));if(!raw)return;const date=new Date(`${raw}T00:00:00`);let key=raw;if(grain==='week'){const day=date.getDay()||7;date.setDate(date.getDate()-day+1);key=date.toISOString().slice(0,10)}else if(grain==='month')key=`${raw.slice(0,7)}-01`;map.set(key,[...(map.get(key)??[]),row])});return[...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,group])=>({date,responses:group.length,nps:calcNps(group).score,experience:experience(group),service:avg(group.map(row=>number(row,A.service))),taste:avg(group.map(row=>number(row,A.taste))),return:returnRate(group)}))},[rows,grain]);
 const radar=[['Загальна',(current.total??0)*10,(previous.total??0)*10],['Атмосфера',(current.ambience??0)*20,(previous.ambience??0)*20],['Сервіс',(current.service??0)*20,(previous.service??0)*20],['Смак',(current.taste??0)*20,(previous.taste??0)*20],['Подача',(current.presentation??0)*20,(previous.presentation??0)*20],['Комфорт',(current.comfort??0)*20,(previous.comfort??0)*20]].map(([name,now,before])=>({name,now,before}));
 const dishStats=useMemo(()=>{const map=new Map<string,{mentions:number;ratings:number[];comments:string[]}>();dishes.forEach(row=>dishCats(text(row,A.dishName)).forEach(name=>{const current=map.get(name)??{mentions:0,ratings:[],comments:[]};current.mentions+=1;const rating=number(row,A.dishRating),comment=text(row,A.dishComment);if(rating!==null)current.ratings.push(rating);if(comment&&!current.comments.includes(comment))current.comments.push(comment);map.set(name,current)}));return[...map.entries()].map(([name,value])=>({name,mentions:value.mentions,rating:avg(value.ratings),comments:value.comments})).sort((a,b)=>b.mentions-a.mentions||(b.rating??0)-(a.rating??0))},[dishes]);
 const positive=useMemo(()=>buildThemes(rows,dishes,'positive'),[rows,dishes]),negative=useMemo(()=>buildThemes(rows,dishes,'negative'),[rows,dishes]);
 const returns=useMemo(()=>{const map=new Map<string,number>();rows.forEach(row=>{const key=text(row,A.ret)||'Без відповіді';map.set(key,(map.get(key)??0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[rows]);
 const genderData=useMemo(()=>{const map=new Map<string,number>();rows.forEach(row=>{const key=text(row,A.gender)||'Не вказано';map.set(key,(map.get(key)??0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[rows]);
 const ageData=useMemo(()=>{const map=new Map<string,number>();rows.forEach(row=>{const key=text(row,A.age)||'Не вказано';map.set(key,(map.get(key)??0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[rows]);
 const source=tab==='general'?rows:dishes,pages=Math.max(1,Math.ceil(source.length/10)),shown=source.slice(page*10,page*10+10);
 useEffect(()=>setPage(0),[tab,filters.period,filters.searchQuery,npsFilter]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] space-y-8 px-4 py-7 md:px-8">
  <header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">ГОСТЬОВИЙ ДОСВІД · GENERAL + DISHES</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Відгуки</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:''}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
  {error&&<div className="rounded-2xl border border-rose-300/20 bg-rose-300/10 p-4 text-rose-100">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={MessageSquareText} label="Відповіді" value={String(current.responses)} current={current.responses} previous={previous.responses}/><Kpi icon={Gauge} label="Experience Index" value={format(current.experience,1)} sub="/100" current={current.experience} previous={previous.experience}/><Kpi icon={Heart} label="NPS" value={current.nps===null?'—':`${current.nps>0?'+':''}${current.nps}`} current={current.nps} previous={previous.nps}/><Kpi icon={Target} label="Точно повернуться" value={`${format(current.return,0)}%`} sub={`Позитивний намір ${format(current.positive,0)}%`} current={current.return} previous={previous.return}/><Kpi icon={Star} label="Загальна оцінка" value={format(current.total,1)} sub="/10" current={current.total} previous={previous.total}/></div>
  <section className="grid gap-6 xl:grid-cols-12"><Panel title="Динаміка досвіду" subtitle="Оберіть метрику й деталізацію" className="xl:col-span-8"><div className="mb-4 flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2">{([{key:'responses',label:'Відповіді'},{key:'experience',label:'Experience'},{key:'nps',label:'NPS'},{key:'service',label:'Сервіс'},{key:'taste',label:'Смак'},{key:'return',label:'Повернення'}]as{key:Metric;label:string}[]).map(item=><button key={item.key} onClick={()=>setMetric(item.key)} className={`rounded-xl px-3 py-2 text-xs font-black ${metric===item.key?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>{item.label}</button>)}</div><div className="flex gap-2">{(['day','week','month']as Grain[]).map(item=><button key={item} onClick={()=>setGrain(item)} className={`rounded-xl px-3 py-2 text-xs font-black ${grain===item?'bg-white/12 text-white':'text-white/45'}`}>{item==='day'?'Дні':item==='week'?'Тижні':'Місяці'}</button>)}</div></div><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid stroke={C.grid} strokeOpacity={.35} vertical={false}/><XAxis dataKey="date" tick={{fill:C.muted,fontSize:11}}/><YAxis tick={{fill:C.muted,fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey={metric} stroke={C.cyan2} fill={C.cyan2} fillOpacity={.14} strokeWidth={3} connectNulls/></AreaChart></ResponsiveContainer></div></Panel>
  <Panel title="Карта досвіду" subtitle="Поточний період проти попереднього" className="xl:col-span-4"><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><RadarChart data={radar} outerRadius="72%"><PolarGrid stroke={C.grid}/><PolarAngleAxis dataKey="name" tick={{fill:'#E7DDE0',fontSize:11}}/><Radar name="Поточний" dataKey="now" stroke={C.cyan2} fill={C.cyan2} fillOpacity={.22}/><Radar name="Попередній" dataKey="before" stroke={C.gold} fill={C.gold} fillOpacity={.05} strokeDasharray="5 5"/><Legend/><Tooltip/></RadarChart></ResponsiveContainer></div></Panel></section>
  <section className="grid gap-6 xl:grid-cols-3"><Panel title="Net Promoter Score" subtitle="Лояльність гостей"><div className="text-7xl font-black tracking-[-.08em] text-[#cfeeed]">{npsData.score===null?'—':`${npsData.score>0?'+':''}${npsData.score}`}</div><p className="mt-3 text-sm text-white/55">{(npsData.score??0)>=70?'Сильна любов до бренду':'Є база лояльності, але важливо опрацювати пасивних і критиків.'}</p></Panel>
  <Panel title="Структура NPS" subtitle="Натисніть на сегмент для фільтра"><div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:'Промоутери',value:npsData.promoters},{name:'Пасивні',value:npsData.passives},{name:'Критики',value:npsData.detractors}]} dataKey="value" innerRadius={55} outerRadius={86} paddingAngle={4} stroke="none">{[C.cyan2,C.gold,C.rose].map(color=><Cell key={color} fill={color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-3 gap-2">{([['Промоутери',npsData.promoters,'promoter'],['Пасивні',npsData.passives,'passive'],['Критики',npsData.detractors,'detractor']]as const).map(([label,value,key])=><button key={key} onClick={()=>setNpsFilter(npsFilter===key?'all':key)} className={`rounded-xl p-3 text-center ${npsFilter===key?'bg-[#cfeeed] text-[#531027]':'bg-black/15'}`}><b className="block text-xl">{value}</b><span className="text-[10px]">{label}</span></button>)}</div></Panel>
  <Panel title="Намір повернутися" subtitle="Фактичні відповіді q15"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={returns} layout="vertical"><CartesianGrid stroke={C.grid} strokeOpacity={.3} horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={130} tick={{fill:C.muted,fontSize:11}}/><Tooltip/><Bar dataKey="value" fill={C.cyan2} radius={[0,10,10,0]}/></BarChart></ResponsiveContainer></div></Panel></section>
  <SectionTitle icon={UtensilsCrossed} eyebrow="КУХНЯ" title="Dish Intelligence" subtitle="Окремий аналіз згадок та оцінок із листа Dishes — без зв’язку з продажами."/>
  <section className="grid gap-6 xl:grid-cols-2"><Panel title="Топ категорій страв" subtitle="Частота згадок і середня оцінка"><div className="space-y-3">{dishStats.slice(0,8).map((dish,index)=><button key={dish.name} onClick={()=>setTheme({key:dish.name,label:dish.name,count:dish.mentions,samples:dish.comments.length?dish.comments:['Без коментарів'],tone:'positive',priority:dish.mentions})} className="grid w-full grid-cols-[32px_1fr_72px] items-center gap-3 rounded-2xl bg-black/12 p-3 text-left hover:bg-white/[.05]"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#cfeeed] text-xs font-black text-[#531027]">{index+1}</span><div><b className="text-sm">{dish.name}</b><p className="text-xs text-white/35">{dish.mentions} згадок</p></div><b className="text-right text-[#cfeeed]">{format(dish.rating,1)}/10</b></button>)}</div></Panel>
  <Panel title="Kitchen watchlist" subtitle="Що тягне оцінки вниз"><div className="space-y-3">{[...dishStats].filter(item=>item.rating!==null).sort((a,b)=>(a.rating??10)-(b.rating??10)).slice(0,6).map(dish=><button key={dish.name} onClick={()=>setTheme({key:dish.name,label:dish.name,count:dish.mentions,samples:dish.comments.length?dish.comments:['Без коментарів'],tone:'negative',priority:dish.mentions})} className="flex w-full justify-between rounded-2xl border border-white/7 bg-black/15 p-4 text-left"><div><b>{dish.name}</b><p className="mt-1 text-xs text-white/35">{dish.mentions} згадок · {dish.comments.length} коментарів</p></div><b className={(dish.rating??10)<8?'text-rose-200':'text-[#cfeeed]'}>{format(dish.rating,1)}</b></button>)}</div></Panel></section>
  <SectionTitle icon={MessageSquareText} eyebrow="VOICE OF GUEST" title="Що люблять і що покращити" subtitle="Тематичний аналіз відкритих відповідей General і коментарів Dishes."/>
  <section className="grid gap-6 xl:grid-cols-2"><Panel title="Що створює вау" subtitle="Love drivers"><div className="grid gap-3 sm:grid-cols-2">{positive.slice(0,8).map(item=><button key={item.key} onClick={()=>setTheme(item)} className="rounded-2xl border border-white/7 bg-black/12 p-4 text-left hover:bg-white/[.05]"><div className="flex justify-between"><b>{item.label}</b><span className="rounded-lg bg-emerald-300/10 px-2 py-1 text-xs font-black text-emerald-200">{item.count}</span></div><p className="mt-3 line-clamp-2 text-xs text-white/35">{item.samples[0]}</p></button>)}</div></Panel>
  <Panel title="Пріоритети покращення" subtitle="Action radar"><div className="space-y-3">{negative.slice(0,8).map((item,index)=>{const max=Math.max(...negative.map(value=>value.priority),1);return <button key={item.key} onClick={()=>setTheme(item)} className="w-full rounded-2xl border border-white/7 bg-black/12 p-4 text-left hover:bg-white/[.05]"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#f3c969]/10 text-xs font-black text-[#f3c969]">{index+1}</span><b className="flex-1">{item.label}</b><span className="text-xs font-black text-[#f3c969]">{item.count}</span></div><div className="mt-3 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-[#f3c969] to-[#f08aa5]" style={{width:`${item.priority/max*100}%`}}/></div></button>})}</div></Panel></section>
  <SectionTitle icon={Users} eyebrow="АУДИТОРІЯ" title="Хто залишає відгуки" subtitle="Структура вибірки та якість заповнення."/>
  <section className="grid gap-6 xl:grid-cols-3"><Panel title="Стать" subtitle="Структура вибірки"><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={genderData} dataKey="value" innerRadius={48} outerRadius={82} paddingAngle={3} stroke="none">{genderData.map((_,index)=><Cell key={index} fill={[C.cyan2,C.rose,C.gold,C.muted][index%4]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></Panel><Panel title="Вікові групи" subtitle="Розподіл відповідей"><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={ageData}><CartesianGrid stroke={C.grid} strokeOpacity={.3} vertical={false}/><XAxis dataKey="name" tick={{fill:C.muted,fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill={C.cyan2} radius={[10,10,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Якість даних" subtitle="Покриття ключових полів"><div className="space-y-5">{([['Стать',rows.filter(row=>text(row,A.gender)).length],['Вік',rows.filter(row=>text(row,A.age)).length],['Коментар',rows.filter(row=>text(row,A.comment)).length],['Dishes',Math.min(rows.length,dishes.length)]]as[string,number][]).map(([label,count])=>{const value=rows.length?count/rows.length*100:0;return <div key={label}><div className="flex justify-between text-xs"><span className="text-white/55">{label}</span><b>{format(value,0)}%</b></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className={`h-full rounded-full ${value>=80?'bg-emerald-300':value>=55?'bg-amber-300':'bg-rose-300'}`} style={{width:`${Math.min(100,value)}%`}}/></div></div>})}</div></Panel></section>
  <SectionTitle icon={BarChart3} eyebrow="DATA EXPLORER" title="Усі сирі відповіді" subtitle="General і Dishes залишаються окремими джерелами."/>
  <Panel title="Дані" subtitle={`${source.length} рядків у вибраному наборі`}><div className="mb-4 flex gap-2"><button onClick={()=>setTab('general')} className={`rounded-xl px-4 py-2 text-xs font-black ${tab==='general'?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>General ({rows.length})</button><button onClick={()=>setTab('dishes')} className={`rounded-xl px-4 py-2 text-xs font-black ${tab==='dishes'?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>Dishes ({dishes.length})</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35">{(tab==='general'?['Дата','ID','Оцінка','NPS','Повернення','Коментар']:['Дата','Response ID','Страва','Оцінка','Коментар']).map(label=><th key={label} className="pb-4">{label}</th>)}</tr></thead><tbody>{shown.map((row,index)=>tab==='general'?<tr key={text(row,A.id)||index} className="border-b border-white/[.07]"><td className="py-4">{parseDate(pick(row,A.date))}</td><td className="max-w-[180px] truncate font-mono text-xs text-white/35">{text(row,A.id)}</td><td className="font-black text-[#cfeeed]">{format(number(row,A.total),0)}</td><td>{format(number(row,A.nps),0)}</td><td>{text(row,A.ret)||'—'}</td><td className="max-w-[360px] truncate text-white/55">{text(row,A.comment)||text(row,A.critical)||'—'}</td></tr>:<tr key={`${text(row,A.dishId)}-${index}`} className="border-b border-white/[.07]"><td className="py-4">{parseDate(pick(row,A.date))}</td><td className="max-w-[180px] truncate font-mono text-xs text-white/35">{text(row,A.dishId)}</td><td className="font-semibold">{text(row,A.dishName)}</td><td className="font-black text-[#cfeeed]">{format(number(row,A.dishRating),0)}/10</td><td className="max-w-[360px] truncate text-white/55">{text(row,A.dishComment)||'—'}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-between text-xs text-white/40"><span>Сторінка {page+1} з {pages}</span><div className="flex gap-2"><button disabled={!page} onClick={()=>setPage(value=>value-1)} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Назад</button><button disabled={page>=pages-1} onClick={()=>setPage(value=>value+1)} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Далі</button></div></div></Panel>
 </div>{theme&&<div className="fixed inset-0 z-[200] flex items-end justify-center bg-black/65 p-3 backdrop-blur-sm md:items-center" onClick={()=>setTheme(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-[30px] border border-white/10 bg-[#410a1b] p-7" onClick={event=>event.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.22em] text-white/35">{theme.tone==='positive'?'Love driver':'Action signal'}</p><h3 className="mt-1 text-2xl font-black">{theme.label}</h3><p className="mt-2 text-sm text-white/45">{theme.count} згадок</p></div><button onClick={()=>setTheme(null)}><X/></button></div><div className="mt-6 space-y-3">{theme.samples.map((sample,index)=><div key={index} className="rounded-2xl border border-white/8 bg-black/15 p-4"><p className="text-[10px] uppercase text-white/30">Приклад {index+1}</p><p className="mt-2 text-sm text-white/75">{sample}</p></div>)}</div></div></div>}</div>;
}

function Panel({title,subtitle,children,className=''}:{title:string;subtitle:string;children:ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><h2 className="text-2xl font-black text-[#d8f4f2]">{title}</h2><p className="mt-1 text-sm text-white/50">{subtitle}</p><div className="mt-5">{children}</div></section>}
function Kpi({icon:Icon,label,value,sub,current,previous}:{icon:any;label:string;value:string;sub?:string;current:number|null;previous:number|null}){const delta=current!==null&&previous!==null?current-previous:null;return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div><div className="mt-2 flex justify-between text-xs"><span className="text-[#cfeeed]/65">{sub||' '}</span><span className={delta===null?'text-white/30':delta>=0?'font-black text-emerald-300':'font-black text-rose-300'}>{delta===null?'—':`${delta>=0?'+':''}${format(delta,Math.abs(delta)<10?1:0)}`}</span></div></div>}
function SectionTitle({icon:Icon,eyebrow,title,subtitle}:{icon:any;eyebrow:string;title:string;subtitle:string}){return <div className="flex gap-3"><div className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06] text-[#cfeeed]"><Icon size={20}/></div><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-white/40">{eyebrow}</p><h2 className="mt-1 text-3xl font-black text-[#d8f4f2]">{title}</h2><p className="mt-1 text-sm text-white/50">{subtitle}</p></div></div>}
