import React,{useEffect,useMemo,useState,type ReactNode}from'react';
import{Activity,AlertTriangle,BarChart3,CheckCircle2,Gauge,Heart,MessageSquareText,RefreshCw,Search,ShieldAlert,Star,Target,TrendingUp,Users,UtensilsCrossed,X}from'lucide-react';
import{Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,PolarAngleAxis,PolarGrid,Radar,RadarChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{buildRange,inRange,fullDate,num as fmtNum,pct}from'./sales/data';
import{useFilters}from'./context/FilterContext';

type Row=Record<string,unknown>;
type Metric='responses'|'nps'|'experience'|'service'|'taste'|'return';
type Grain='day'|'week'|'month';
type Theme={key:string;label:string;count:number;samples:string[];tone:'positive'|'negative';priority:number};
const API_URL=import.meta.env.VITE_API_URL||`${import.meta.env.BASE_URL||'/'}data.json`;
const C={cyan:'#CFF3F2',cyan2:'#8DE0DE',gold:'#F3C969',rose:'#F08AA5',green:'#79D7B4',muted:'#CBB5BD',grid:'#7D3046'};
const A={id:['ID','Response ID'],date:['Timestamp','Date'],total:['Total Score (q1)','Q1_General'],ambience:['Ambience Rating (q2)','Q2_Atmosphere_Rating'],ambienceText:['Ambience Matches (q3)','Q3_Atmosphere_Likes'],hall:['Hall Improvements (q4)','Q4_Atmosphere_Improvements'],service:['Service Rating (q5)','Q5_Service_Rating'],staff:['Staff Comfort (q6)','Q6_Service_Comfort'],serviceText:['Service Improvements (q7)','Q7_Service_Improvements'],taste:['Food Taste (q8)','Q8_Food_Taste'],presentation:['Food Presentation (q9)','Q9_Food_Presentation'],comfort:['Stay Comfort (q12)','Q12_Comfort_Rating'],discomfort:['Stay Discomfort (q13)','Q13_Comfort_Dislikes'],critical:['CRITICAL FIX (q14)','Q14_Priority_Fix'],ret:['Will Return (q15)','Q15_Return_Intent'],nps:['NPS Score (q16)','Q16_NPS'],comment:['User Comment (q17)','Q17_Comments'],gender:['Gender'],age:['Age Group','AgeGroup'],dishId:['Response ID','ID'],dishName:['Dish Name'],dishRating:['Dish Rating'],dishComment:['Dish Comment']}as const;
const NEG=[['menu','Меню / асортимент',['меню','позиці','вибір','асортимент','дитяч']],['bar','Бар / алкоголь',['алког','пиво','коктейл','бар']],['speed','Швидкість видачі',['швидк','очікуван','довго','винесен','приготуван']],['service','Уважність / сервіс',['уважн','офіціант','персонал','розрахунк','непорозум']],['climate','Температура / клімат',['температур','прохолод','холод','жарко']],['hall','Столи / ергономіка',['столи','стільчик','близько','прохід']],['access','Доступність / родини',['доступн','маломоб','підгуз','дитин','малюк','куточок']],['ops','Операційні дрібниці',['сервет','зубочист','спеці','вода','антисеп','урна','смітник']],['taste','Смак / рецептура',['соус','прожарк','м’яс',"м'яс",'смак','теплим','стейк не стейк']],['light','Світло / музика',['освітлен','світло','музик','гучн']]]as const;
const POS=[['staff','Привітність персоналу',['привітн','офіціант','персонал','команда','адміністратор']],['interior','Інтер’єр',['інтер’єр',"інтер'єр",'декор']],['clean','Чистота',['чистот']],['music','Музика',['музик','гучн']],['light','Освітлення',['освітлен','світло']],['food','Смак страв',['смач','смак','неперевершен']],['value','Ціна / цінність',['дуже вигідно','ціна повністю виправдана']],['overall','Усе сподобалось',['усе сподобалось','все супер','все чудово','бездоган']]]as const;
const pick=(r:Row,keys:readonly string[])=>{for(const k of keys){const v=r[k];if(v!==undefined&&v!==null&&v!=='')return v}};
const text=(r:Row,keys:readonly string[])=>String(pick(r,keys)??'').trim();
const number=(r:Row,keys:readonly string[])=>{const n=Number(String(pick(r,keys)??'').replace(',','.'));return Number.isFinite(n)?n:null};
const parseDate=(value:unknown)=>{const raw=String(value??'').trim();const m=raw.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(raw);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};
const avg=(a:(number|null)[])=>{const v=a.filter((x):x is number=>x!==null);return v.length?v.reduce((s,x)=>s+x,0)/v.length:null};
const norm=(s:string)=>s.toLowerCase().replace(/[’ʼ]/g,"'").replace(/\s+/g,' ').trim();
const nps=(rows:Row[])=>{let promoters=0,passives=0,detractors=0;rows.forEach(r=>{const n=number(r,A.nps);if(n===null)return;n>=9?promoters++:n<=6?detractors++:passives++});const t=promoters+passives+detractors;return{score:t?Math.round((promoters-detractors)/t*100):null,promoters,passives,detractors}};
const experience=(rows:Row[])=>{const vals=rows.map(r=>avg([number(r,A.total)!==null?number(r,A.total)!/10:null,...[A.ambience,A.service,A.taste,A.presentation,A.comfort].map(k=>number(r,k)!==null?number(r,k)!/5:null)])).filter((x):x is number=>x!==null);const v=avg(vals);return v===null?null:v*100};
const returnRate=(rows:Row[],strong=true)=>{const a=rows.map(r=>text(r,A.ret).toLowerCase()).filter(Boolean);return a.length?a.filter(x=>strong?x.includes('обов'):x.includes('обов')||x.includes('скоріш')).length/a.length*100:null};
const metrics=(rows:Row[])=>({responses:rows.length,nps:nps(rows).score,experience:experience(rows),total:avg(rows.map(r=>number(r,A.total))),ambience:avg(rows.map(r=>number(r,A.ambience))),service:avg(rows.map(r=>number(r,A.service))),taste:avg(rows.map(r=>number(r,A.taste))),presentation:avg(rows.map(r=>number(r,A.presentation))),comfort:avg(rows.map(r=>number(r,A.comfort))),return:returnRate(rows),positive:returnRate(rows,false)});
const dishCats=(raw:string)=>{const s=norm(raw),out:string[]=[];const add=(v:string)=>!out.includes(v)&&out.push(v);if(s.includes('стейк')&&s.includes('боул'))add('Стейк-боул');if(s.includes('бургер'))add('Бургер');if(s.includes('тако'))add('Тако');if(s.includes('мелт'))add('Мелт');if(s.includes('удон'))add('Удон');if(s.includes('суп')||s.includes('колаген'))add('Колагеновий суп');if(s.includes('салат'))add('Салат');if(s.includes('боул')&&!out.includes('Стейк-боул'))add('Боул');if(s.includes('стейк')&&!out.includes('Стейк-боул'))add('Стейк');if(!out.length&&raw&&s!=='кайф')add(raw.length>34?`${raw.slice(0,34)}…`:raw);return out};
const buildThemes=(rows:Row[],dishes:Row[],tone:'positive'|'negative'):Theme[]=>{const rules=tone==='positive'?POS:NEG,map=new Map<string,{count:number;samples:string[];critical:number}>();rows.forEach(r=>{const source=(tone==='positive'?[text(r,A.ambienceText),text(r,A.staff),text(r,A.comment)]:[text(r,A.hall),text(r,A.serviceText),text(r,A.discomfort),text(r,A.critical)]).filter(Boolean).join(' • '),n=norm(source);if(!n)return;rules.forEach(([key,,words])=>{if(!words.some(w=>n.includes(norm(w))))return;const x=map.get(key)||{count:0,samples:[],critical:0};x.count++;if(source&&!x.samples.includes(source)&&x.samples.length<5)x.samples.push(source);if(tone==='negative'&&text(r,A.critical))x.critical++;map.set(key,x)})});if(tone==='negative')dishes.forEach(r=>{const source=text(r,A.dishComment),n=norm(source);rules.forEach(([key,,words])=>{if(!source||!words.some(w=>n.includes(norm(w))))return;const x=map.get(key)||{count:0,samples:[],critical:0};x.count++;if(!x.samples.includes(source)&&x.samples.length<5)x.samples.push(source);map.set(key,x)})});return rules.map(([key,label])=>{const x=map.get(key)||{count:0,samples:[],critical:0};return{key,label,count:x.count,samples:x.samples,tone,priority:x.count*10+x.critical*6}}).filter(x=>x.count).sort((a,b)=>b.priority-a.priority)};
const tooltipStyle={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};

export default function FeedbackDashboardGlobal(){
 const[data,setData]=useState<{general:Row[];dishes:Row[]}>({general:[],dishes:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[metric,setMetric]=useState<Metric>('experience'),[grain,setGrain]=useState<Grain>('day'),[theme,setTheme]=useState<Theme|null>(null),[npsFilter,setNpsFilter]=useState<'all'|'promoter'|'passive'|'detractor'>('all'),[tab,setTab]=useState<'general'|'dishes'>('general'),[page,setPage]=useState(0);
 const{filters}=useFilters();
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`${API_URL}${API_URL.includes('?')?'&':'?'}_=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();setData({general:Array.isArray(j.general)?j.general:[],dishes:Array.isArray(j.dishes)?j.dishes:[]})}catch(e){console.error(e);setError('Не вдалося завантажити General і Dishes.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const latest=useMemo(()=>data.general.map(r=>parseDate(pick(r,A.date))).filter(Boolean).sort().at(-1)||'',[data.general]);
 const range=useMemo(()=>buildRange(filters.period,latest?new Date(`${latest}T00:00:00`):new Date()),[filters.period,latest]);
 const baseRows=useMemo(()=>data.general.filter(r=>{const d=parseDate(pick(r,A.date));if(d&&!inRange(d,range.from,range.to))return false;const q=filters.searchQuery.trim().toLowerCase();if(q&&!Object.values(r).some(v=>String(v??'').toLowerCase().includes(q)))return false;const c=number(r,A.nps);if(npsFilter==='promoter'&&(c===null||c<9))return false;if(npsFilter==='passive'&&(c===null||c<7||c>8))return false;if(npsFilter==='detractor'&&(c===null||c>6))return false;return true}),[data.general,range,filters.searchQuery,npsFilter]);
 const previousRows=useMemo(()=>data.general.filter(r=>{const d=parseDate(pick(r,A.date));return d?inRange(d,range.comparisonFrom,range.comparisonTo):false}),[data.general,range]);
 const ids=useMemo(()=>new Set(baseRows.map(r=>text(r,A.id)).filter(Boolean)),[baseRows]);
 const dishes=useMemo(()=>data.dishes.filter(r=>ids.has(text(r,A.dishId))||inRange(parseDate(pick(r,A.date)),range.from,range.to)),[data.dishes,ids,range]);
 const m=useMemo(()=>metrics(baseRows),[baseRows]),pm=useMemo(()=>metrics(previousRows),[previousRows]),npsData=useMemo(()=>nps(baseRows),[baseRows]);
 const trend=useMemo(()=>{const map=new Map<string,Row[]>();baseRows.forEach(r=>{const d=parseDate(pick(r,A.date));if(!d)return;const dt=new Date(`${d}T00:00:00`);let key=d;if(grain==='week'){const day=dt.getDay()||7;dt.setDate(dt.getDate()-day+1);key=dt.toISOString().slice(0,10)}else if(grain==='month')key=`${d.slice(0,7)}-01`;map.set(key,[...(map.get(key)||[]),r])});return[...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,rows])=>({date,responses:rows.length,nps:nps(rows).score,experience:experience(rows),service:avg(rows.map(r=>number(r,A.service))),taste:avg(rows.map(r=>number(r,A.taste))),return:returnRate(rows)}))},[baseRows,grain]);
 const radar=[['Загальна',(m.total||0)*10,(pm.total||0)*10],['Атмосфера',(m.ambience||0)*20,(pm.ambience||0)*20],['Сервіс',(m.service||0)*20,(pm.service||0)*20],['Смак',(m.taste||0)*20,(pm.taste||0)*20],['Подача',(m.presentation||0)*20,(pm.presentation||0)*20],['Комфорт',(m.comfort||0)*20,(pm.comfort||0)*20]].map(([name,current,previous])=>({name,current,previous}));
 const dishStats=useMemo(()=>{const map=new Map<string,{mentions:number;ratings:number[];comments:string[]}>();dishes.forEach(r=>dishCats(text(r,A.dishName)).forEach(name=>{const x=map.get(name)||{mentions:0,ratings:[],comments:[]};x.mentions++;const rating=number(r,A.dishRating),comment=text(r,A.dishComment);if(rating!==null)x.ratings.push(rating);if(comment&&!x.comments.includes(comment))x.comments.push(comment);map.set(name,x)}));return[...map.entries()].map(([name,x])=>({name,mentions:x.mentions,rating:avg(x.ratings),comments:x.comments})).sort((a,b)=>b.mentions-a.mentions||(b.rating||0)-(a.rating||0))},[dishes]);
 const positive=useMemo(()=>buildThemes(baseRows,dishes,'positive'),[baseRows,dishes]),negative=useMemo(()=>buildThemes(baseRows,dishes,'negative'),[baseRows,dishes]);
 const returns=useMemo(()=>{const map=new Map<string,number>();baseRows.forEach(r=>{const k=text(r,A.ret)||'Без відповіді';map.set(k,(map.get(k)||0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[baseRows]);
 const genderData=useMemo(()=>{const map=new Map<string,number>();baseRows.forEach(r=>{const k=text(r,A.gender)||'Не вказано';map.set(k,(map.get(k)||0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[baseRows]);
 const ageData=useMemo(()=>{const map=new Map<string,number>();baseRows.forEach(r=>{const k=text(r,A.age)||'Не вказано';map.set(k,(map.get(k)||0)+1)});return[...map.entries()].map(([name,value])=>({name,value}))},[baseRows]);
 const source=tab==='general'?baseRows:dishes,pages=Math.max(1,Math.ceil(source.length/10)),shown=source.slice(page*10,page*10+10);
 useEffect(()=>setPage(0),[tab,filters.period,filters.searchQuery,npsFilter]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] space-y-8 px-4 py-7 md:px-8">
  <header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">ГОСТЬОВИЙ ДОСВІД · GENERAL + DISHES</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Відгуки</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:''}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
  {error&&<div className="rounded-2xl border border-rose-300/20 bg-rose-300/10 p-4 text-rose-100">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Kpi icon={MessageSquareText} label="Відповіді" value={String(m.responses)} current={m.responses} previous={pm.responses}/><Kpi icon={Gauge} label="Experience Index" value={f(m.experience,1)} sub="/100" current={m.experience} previous={pm.experience}/><Kpi icon={Heart} label="NPS" value={m.nps===null?'—':`${m.nps>0?'+':''}${m.nps}`} current={m.nps} previous={pm.nps}/><Kpi icon={Target} label="Точно повернуться" value={`${f(m.return,0)}%`} sub={`Позитивний намір ${f(m.positive,0)}%`} current={m.return} previous={pm.return}/><Kpi icon={Star} label="Загальна оцінка" value={f(m.total,1)} sub="/10" current={m.total} previous={pm.total}/></div>
  <section className="grid gap-6 xl:grid-cols-12"><Panel title="Динаміка досвіду" subtitle="Оберіть метрику й деталізацію" className="xl:col-span-8"><div className="mb-4 flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2">{([{key:'responses',label:'Відповіді'},{key:'experience',label:'Experience'},{key:'nps',label:'NPS'},{key:'service',label:'Сервіс'},{key:'taste',label:'Смак'},{key:'return',label:'Повернення'}]as{key:Metric;label:string}[]).map(x=><button key={x.key} onClick={()=>setMetric(x.key)} className={`rounded-xl px-3 py-2 text-xs font-black ${metric===x.key?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>{x.label}</button>)}</div><div className="flex gap-2">{(['day','week','month']as Grain[]).map(x=><button key={x} onClick={()=>setGrain(x)} className={`rounded-xl px-3 py-2 text-xs font-black ${grain===x?'bg-white/12 text-white':'text-white/45'}`}>{x==='day'?'Дні':x==='week'?'Тижні':'Місяці'}</button>)}</div></div><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid stroke={C.grid} strokeOpacity={.35} vertical={false}/><XAxis dataKey="date" tick={{fill:C.muted,fontSize:11}}/><YAxis tick={{fill:C.muted,fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey={metric} stroke={C.cyan2} fill={C.cyan2} fillOpacity={.14} strokeWidth={3} connectNulls/></AreaChart></ResponsiveContainer></div></Panel>
  <Panel title="Карта досвіду" subtitle="Поточний період проти попереднього" className="xl:col-span-4"><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><RadarChart data={radar} outerRadius="72%"><PolarGrid stroke={C.grid}/><PolarAngleAxis dataKey="name" tick={{fill:'#E7DDE0',fontSize:11}}/><Radar name="Поточний" dataKey="current" stroke={C.cyan2} fill={C.cyan2} fillOpacity={.22}/><Radar name="Попередній" dataKey="previous" stroke={C.gold} fill={C.gold} fillOpacity={.05} strokeDasharray="5 5"/><Legend/><Tooltip/></RadarChart></ResponsiveContainer></div></Panel></section>
  <section className="grid gap-6 xl:grid-cols-3"><Panel title="Net Promoter Score" subtitle="Лояльність гостей"><div className="text-7xl font-black tracking-[-.08em] text-[#cfeeed]">{npsData.score===null?'—':`${npsData.score>0?'+':''}${npsData.score}`}</div><p className="mt-3 text-sm text-white/55">{(npsData.score||0)>=70?'Сильна любов до бренду':'Є база лояльності, але важливо опрацювати пасивних і критиків.'}</p></Panel>
  <Panel title="Структура NPS" subtitle="Натисніть на сегмент для фільтра"><div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:'Промоутери',value:npsData.promoters},{name:'Пасивні',value:npsData.passives},{name:'Критики',value:npsData.detractors}]} dataKey="value" innerRadius={55} outerRadius={86} paddingAngle={4} stroke="none">{[C.cyan2,C.gold,C.rose].map(c=><Cell key={c} fill={c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-3 gap-2">{[['Промоутери',npsData.promoters,'promoter'],['Пасивні',npsData.passives,'passive'],['Критики',npsData.detractors,'detractor']].map(([l,v,k])=><button key={String(k)} onClick={()=>setNpsFilter(npsFilter===k?'all':k as any)} className={`rounded-xl p-3 text-center ${npsFilter===k?'bg-[#cfeeed] text-[#531027]':'bg-black/15'}`}><b className="block text-xl">{v}</b><span className="text-[10px]">{l}</span></button>)}</div></Panel>
  <Panel title="Намір повернутися" subtitle="Фактичні відповіді q15"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={returns} layout="vertical"><CartesianGrid stroke={C.grid} strokeOpacity={.3} horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={130} tick={{fill:C.muted,fontSize:11}}/><Tooltip/><Bar dataKey="value" fill={C.cyan2} radius={[0,10,10,0]}/></BarChart></ResponsiveContainer></div></Panel></section>
  <SectionTitle icon={UtensilsCrossed} eyebrow="КУХНЯ" title="Dish Intelligence" subtitle="Окремий аналіз згадок та оцінок із листа Dishes — без зв’язку з продажами."/>
  <section className="grid gap-6 xl:grid-cols-2"><Panel title="Топ категорій страв" subtitle="Частота згадок і середня оцінка"><div className="space-y-3">{dishStats.slice(0,8).map((d,i)=><button key={d.name} onClick={()=>setTheme({key:d.name,label:d.name,count:d.mentions,samples:d.comments.length?d.comments:['Без коментарів'],tone:'positive',priority:d.mentions})} className="grid w-full grid-cols-[32px_1fr_72px] items-center gap-3 rounded-2xl bg-black/12 p-3 text-left hover:bg-white/[.05]"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#cfeeed] text-xs font-black text-[#531027]">{i+1}</span><div><b className="text-sm">{d.name}</b><p className="text-xs text-white/35">{d.mentions} згадок</p></div><b className="text-right text-[#cfeeed]">{f(d.rating,1)}/10</b></button>)}</div></Panel>
  <Panel title="Kitchen watchlist" subtitle="Що тягне оцінки вниз"><div className="space-y-3">{[...dishStats].filter(x=>x.rating!==null).sort((a,b)=>(a.rating||10)-(b.rating||10)).slice(0,6).map(d=><button key={d.name} onClick={()=>setTheme({key:d.name,label:d.name,count:d.mentions,samples:d.comments.length?d.comments:['Без коментарів'],tone:'negative',priority:d.mentions})} className="flex w-full justify-between rounded-2xl border border-white/7 bg-black/15 p-4 text-left"><div><b>{d.name}</b><p className="mt-1 text-xs text-white/35">{d.mentions} згадок · {d.comments.length} коментарів</p></div><b className={(d.rating||10)<8?'text-rose-200':'text-[#cfeeed]'}>{f(d.rating,1)}</b></button>)}</div></Panel></section>
  <SectionTitle icon={MessageSquareText} eyebrow="VOICE OF GUEST" title="Що люблять і що покращити" subtitle="Тематичний аналіз відкритих відповідей General і коментарів Dishes."/>
  <section className="grid gap-6 xl:grid-cols-2"><Panel title="Що створює вау" subtitle="Love drivers"><div className="grid gap-3 sm:grid-cols-2">{positive.slice(0,8).map(t=><button key={t.key} onClick={()=>setTheme(t)} className="rounded-2xl border border-white/7 bg-black/12 p-4 text-left hover:bg-white/[.05]"><div className="flex justify-between"><b>{t.label}</b><span className="rounded-lg bg-emerald-300/10 px-2 py-1 text-xs font-black text-emerald-200">{t.count}</span></div><p className="mt-3 line-clamp-2 text-xs text-white/35">{t.samples[0]}</p></button>)}</div></Panel>
  <Panel title="Пріоритети покращення" subtitle="Action radar"><div className="space-y-3">{negative.slice(0,8).map((t,i)=>{const max=Math.max(...negative.map(x=>x.priority),1);return <button key={t.key} onClick={()=>setTheme(t)} className="w-full rounded-2xl border border-white/7 bg-black/12 p-4 text-left hover:bg-white/[.05]"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#f3c969]/10 text-xs font-black text-[#f3c969]">{i+1}</span><b className="flex-1">{t.label}</b><span className="text-xs font-black text-[#f3c969]">{t.count}</span></div><div className="mt-3 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-[#f3c969] to-[#f08aa5]" style={{width:`${t.priority/max*100}%`}}/></div></button>})}</div></Panel></section>
  <SectionTitle icon={Users} eyebrow="АУДИТОРІЯ" title="Хто залишає відгуки" subtitle="Структура вибірки та якість заповнення."/>
  <section className="grid gap-6 xl:grid-cols-3"><Panel title="Стать" subtitle="Структура вибірки"><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={genderData} dataKey="value" innerRadius={48} outerRadius={82} paddingAngle={3} stroke="none">{genderData.map((_,i)=><Cell key={i} fill={[C.cyan2,C.rose,C.gold,C.muted][i%4]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></Panel>
  <Panel title="Вікові групи" subtitle="Розподіл відповідей"><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={ageData}><CartesianGrid stroke={C.grid} strokeOpacity={.3} vertical={false}/><XAxis dataKey="name" tick={{fill:C.muted,fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill={C.cyan2} radius={[10,10,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
  <Panel title="Якість даних" subtitle="Покриття ключових полів"><div className="space-y-5">{[['Стать',baseRows.filter(r=>text(r,A.gender)).length],['Вік',baseRows.filter(r=>text(r,A.age)).length],['Коментар',baseRows.filter(r=>text(r,A.comment)).length],['Dishes',Math.min(baseRows.length,dishes.length)]].map(([l,c])=>{const v=baseRows.length?Number(c)/baseRows.length*100:0;return <div key={String(l)}><div className="flex justify-between text-xs"><span className="text-white/55">{l}</span><b>{f(v,0)}%</b></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className={`h-full rounded-full ${v>=80?'bg-emerald-300':v>=55?'bg-amber-300':'bg-rose-300'}`} style={{width:`${Math.min(100,v)}%`}}/></div></div>})}</div></Panel></section>
  <SectionTitle icon={BarChart3} eyebrow="DATA EXPLORER" title="Усі сирі відповіді" subtitle="General і Dishes залишаються окремими джерелами."/>
  <Panel title="Дані" subtitle={`${source.length} рядків у вибраному наборі`}><div className="mb-4 flex gap-2"><button onClick={()=>setTab('general')} className={`rounded-xl px-4 py-2 text-xs font-black ${tab==='general'?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>General ({baseRows.length})</button><button onClick={()=>setTab('dishes')} className={`rounded-xl px-4 py-2 text-xs font-black ${tab==='dishes'?'bg-[#cfeeed] text-[#531027]':'border border-white/10 text-white/55'}`}>Dishes ({dishes.length})</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35">{(tab==='general'?['Дата','ID','Оцінка','NPS','Повернення','Коментар']:['Дата','Response ID','Страва','Оцінка','Коментар']).map(x=><th key={x} className="pb-4">{x}</th>)}</tr></thead><tbody>{shown.map((r,i)=>tab==='general'?<tr key={text(r,A.id)||i} className="border-b border-white/[.07]"><td className="py-4">{parseDate(pick(r,A.date))}</td><td className="max-w-[180px] truncate font-mono text-xs text-white/35">{text(r,A.id)}</td><td className="font-black text-[#cfeeed]">{f(number(r,A.total),0)}</td><td>{f(number(r,A.nps),0)}</td><td>{text(r,A.ret)||'—'}</td><td className="max-w-[360px] truncate text-white/55">{text(r,A.comment)||text(r,A.critical)||'—'}</td></tr>:<tr key={`${text(r,A.dishId)}-${i}`} className="border-b border-white/[.07]"><td className="py-4">{parseDate(pick(r,A.date))}</td><td className="max-w-[180px] truncate font-mono text-xs text-white/35">{text(r,A.dishId)}</td><td className="font-semibold">{text(r,A.dishName)}</td><td className="font-black text-[#cfeeed]">{f(number(r,A.dishRating),0)}/10</td><td className="max-w-[360px] truncate text-white/55">{text(r,A.dishComment)||'—'}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-between text-xs text-white/40"><span>Сторінка {page+1} з {pages}</span><div className="flex gap-2"><button disabled={!page} onClick={()=>setPage(p=>p-1)} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Назад</button><button disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Далі</button></div></div></Panel>
 </div>{theme&&<div className="fixed inset-0 z-[200] flex items-end justify-center bg-black/65 p-3 backdrop-blur-sm md:items-center" onClick={()=>setTheme(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-[30px] border border-white/10 bg-[#410a1b] p-7" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-[.22em] text-white/35">{theme.tone==='positive'?'Love driver':'Action signal'}</p><h3 className="mt-1 text-2xl font-black">{theme.label}</h3><p className="mt-2 text-sm text-white/45">{theme.count} згадок</p></div><button onClick={()=>setTheme(null)}><X/></button></div><div className="mt-6 space-y-3">{theme.samples.map((s,i)=><div key={i} className="rounded-2xl border border-white/8 bg-black/15 p-4"><p className="text-[10px] uppercase text-white/30">Приклад {i+1}</p><p className="mt-2 text-sm text-white/75">{s}</p></div>)}</div></div></div>}</div>
}
const f=(v:number|null,d=1)=>v===null||!Number.isFinite(v)?'—':new Intl.NumberFormat('uk-UA',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
function Panel({title,subtitle,children,className=''}:{title:string;subtitle:string;children:ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><h2 className="text-2xl font-black text-[#d8f4f2]">{title}</h2><p className="mt-1 text-sm text-white/50">{subtitle}</p><div className="mt-5">{children}</div></section>}
function Kpi({icon:Icon,label,value,sub,current,previous}:{icon:any;label:string;value:string;sub?:string;current:number|null;previous:number|null}){const delta=current!==null&&previous!==null?current-previous:null;return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div><div className="mt-2 flex justify-between text-xs"><span className="text-[#cfeeed]/65">{sub||' '}</span><span className={delta===null?'text-white/30':delta>=0?'font-black text-emerald-300':'font-black text-rose-300'}>{delta===null?'—':`${delta>=0?'+':''}${f(delta,Math.abs(delta)<10?1:0)}`}</span></div></div>}
function SectionTitle({icon:Icon,eyebrow,title,subtitle}:{icon:any;eyebrow:string;title:string;subtitle:string}){return <div className="flex gap-3"><div className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06] text-[#cfeeed]"><Icon size={20}/></div><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-white/40">{eyebrow}</p><h2 className="mt-1 text-3xl font-black text-[#d8f4f2]">{title}</h2><p className="mt-1 text-sm text-white/50">{subtitle}</p></div></div>}
