import React,{useEffect,useMemo,useState}from'react';
import{BarChart3,RefreshCw,Star,Horse,Puzzle,Dog,ArrowLeft,TrendingUp,UtensilsCrossed}from'lucide-react';
import{Payload,PeriodKey,PERIODS,buildRange,inRange,money,num,pct,fullDate,shortDate}from'./sales/data';
import{cleanProductRows,normalizeProductName}from'./sales/semantic';

type MenuRow={productName:string;category:string;quantity:number;revenue:number;markup:number;cost:number;avgPrice:number;unitMarkup:number;markupPercent:number;revenueShare:number;quantityShare:number;abcRevenue:'A'|'B'|'C';abcQuantity:'A'|'B'|'C';abcMarkup:'A'|'B'|'C';segment:'Star'|'Plow Horse'|'Puzzle'|'Dog'};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const segmentMeta={
 Star:{label:'Stars',icon:Star,helper:'Високий попит · висока націнка',className:'border-emerald-200/20 bg-emerald-100/10 text-emerald-100'},
 'Plow Horse':{label:'Plow Horses',icon:Horse,helper:'Високий попит · нижча націнка',className:'border-amber-200/20 bg-amber-100/10 text-amber-100'},
 Puzzle:{label:'Puzzles',icon:Puzzle,helper:'Низький попит · висока націнка',className:'border-sky-200/20 bg-sky-100/10 text-sky-100'},
 Dog:{label:'Dogs',icon:Dog,helper:'Низький попит · нижча націнка',className:'border-rose-200/20 bg-rose-100/10 text-rose-100'}
}as const;

function classifyABC<T extends MenuRow>(rows:T[],field:'revenue'|'quantity'|'markup'){
 const sorted=[...rows].sort((a,b)=>b[field]-a[field]);const total=sorted.reduce((s,x)=>s+x[field],0);let acc=0;const map=new Map<string,'A'|'B'|'C'>();
 sorted.forEach(x=>{acc+=x[field];const share=total?acc/total:1;map.set(x.productName,share<=.8?'A':share<=.95?'B':'C')});return map;
}
function median(values:number[]){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-xl font-black text-[#d8f4f2] md:text-2xl">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}

export default function MenuDashboard(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<PeriodKey>('current_month'),[segment,setSegment]=useState<'all'|MenuRow['segment']>('all');
 const load=async()=>{setLoading(true);try{const r=await fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json()as Payload;if(Number(p.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(period,new Date()),[period]);
 const rows=useMemo<MenuRow[]>(()=>{if(!data)return[];const source=cleanProductRows(data.productsDaily.filter(x=>inRange(x.date,range.from,range.to)) as any);const m=new Map<string,any>();
 source.forEach((x:any)=>{const name=normalizeProductName(x.productName),key=name.toLowerCase();const cur=m.get(key)||{productName:name,category:x.category||'Без категорії',quantity:0,revenue:0,markup:0};cur.quantity+=Number(x.quantity)||0;cur.revenue+=Number(x.revenue)||0;cur.markup+=Number(x.markup)||0;if((!cur.category||cur.category==='Без категорії')&&x.category)cur.category=x.category;m.set(key,cur)});
 const base=[...m.values()].filter(x=>x.quantity>0&&x.revenue>0).map(x=>({...x,cost:x.revenue-x.markup,avgPrice:x.revenue/x.quantity,unitMarkup:x.markup/x.quantity,markupPercent:x.revenue?x.markup/x.revenue*100:0,revenueShare:0,quantityShare:0,abcRevenue:'C',abcQuantity:'C',abcMarkup:'C',segment:'Dog'}));
 const revTotal=base.reduce((s,x)=>s+x.revenue,0),qtyTotal=base.reduce((s,x)=>s+x.quantity,0),popMedian=median(base.map(x=>x.quantity)),marginMedian=median(base.map(x=>x.unitMarkup));
 const abcR=classifyABC(base as MenuRow[],'revenue'),abcQ=classifyABC(base as MenuRow[],'quantity'),abcM=classifyABC(base as MenuRow[],'markup');
 return base.map(x=>{const popular=x.quantity>=popMedian,profitable=x.unitMarkup>=marginMedian;return{...x,revenueShare:revTotal?x.revenue/revTotal*100:0,quantityShare:qtyTotal?x.quantity/qtyTotal*100:0,abcRevenue:abcR.get(x.productName)||'C',abcQuantity:abcQ.get(x.productName)||'C',abcMarkup:abcM.get(x.productName)||'C',segment:popular?(profitable?'Star':'Plow Horse'):(profitable?'Puzzle':'Dog')}}).sort((a,b)=>b.revenue-a.revenue) as MenuRow[]},[data,range]);
 const filtered=segment==='all'?rows:rows.filter(x=>x.segment===segment);const totalRevenue=rows.reduce((s,x)=>s+x.revenue,0),totalMarkup=rows.reduce((s,x)=>s+x.markup,0),totalQty=rows.reduce((s,x)=>s+x.quantity,0);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-6 md:px-8 md:py-9">
 <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><a href="#dashboard_sales" className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-white/50 hover:text-white"><ArrowLeft size={16}/> Sales BI</a><div className="flex items-center gap-3 text-[#cfeeed]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06]"><UtensilsCrossed size={23}/></div><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">MARMOO Intelligence</p><h1 className="text-4xl font-black md:text-5xl">Menu Intelligence</h1></div></div><p className="mt-4 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити</button></header>
 <div className="mb-6 overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{PERIODS.map(p=><button key={p.key} onClick={()=>setPeriod(p.key)} className={`rounded-xl border px-4 py-2.5 text-sm font-bold ${period===p.key?'border-[#cfeeed] bg-[#cfeeed] text-[#5b0b25]':'border-white/10 bg-white/[.05] text-white/65'}`}>{p.label}</button>)}</div></div>
 <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(segmentMeta).map(([key,meta])=>{const count=rows.filter(x=>x.segment===key).length,Icon=meta.icon;return <button key={key} onClick={()=>setSegment(segment===key?'all':key as MenuRow['segment'])} className={`rounded-[24px] border p-5 text-left ${meta.className} ${segment===key?'ring-2 ring-[#cfeeed]':''}`}><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] opacity-65">{meta.label}</p><div className="mt-2 text-3xl font-black">{count}</div></div><Icon size={28}/></div><p className="mt-3 text-xs opacity-60">{meta.helper}</p></button>})}</div>
 <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-[#cfeeed] p-5 text-[#531027]"><p className="text-xs font-black uppercase opacity-60">Оборот меню</p><div className="mt-2 text-3xl font-black">{money(totalRevenue)}</div></div><div className="rounded-2xl bg-[#f6eee8] p-5 text-[#531027]"><p className="text-xs font-black uppercase opacity-60">Продано</p><div className="mt-2 text-3xl font-black">{num(totalQty)} од.</div></div><div className="rounded-2xl bg-[#cfeeed] p-5 text-[#531027]"><p className="text-xs font-black uppercase opacity-60">Націнка</p><div className="mt-2 text-3xl font-black">{money(totalMarkup)}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-black uppercase text-white/45">Позицій у аналізі</p><div className="mt-2 text-3xl font-black">{rows.length}</div></div></div>
 <Panel title="Матриця Menu Engineering" subtitle="Популярність визначається медіаною кількості, прибутковість — медіаною націнки на одиницю"><div className="grid gap-4 lg:grid-cols-2">{Object.entries(segmentMeta).map(([key,meta])=>{const list=rows.filter(x=>x.segment===key).slice(0,8),Icon=meta.icon;return <div key={key} className={`rounded-2xl border p-4 ${meta.className}`}><div className="mb-3 flex items-center justify-between"><div><h3 className="font-black">{meta.label}</h3><p className="text-xs opacity-55">{meta.helper}</p></div><Icon size={22}/></div><div className="space-y-2">{list.map(x=><div key={x.productName} className="flex items-center justify-between rounded-xl bg-black/10 px-3 py-2 text-sm"><span className="max-w-[65%] font-semibold">{x.productName}</span><span className="text-right"><b>{num(x.quantity)} од.</b><br/><span className="text-xs opacity-55">{money(x.unitMarkup)}/од.</span></span></div>)}</div></div>})}</div></Panel>
 <Panel title="Повний рейтинг страв" subtitle={segment==='all'?range.label:`${range.label} · ${segmentMeta[segment].label}`} className="mt-5"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Страва</th><th>Категорія</th><th>Сегмент</th><th className="text-right">Кількість</th><th className="text-right">Оборот</th><th className="text-right">Націнка</th><th className="text-right">Націнка/од.</th><th className="text-right">Націнка %</th><th className="text-center">ABC оборот</th><th className="text-center">ABC к-сть</th><th className="text-center">ABC націнка</th></tr></thead><tbody>{filtered.map((x,i)=><tr key={x.productName} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-semibold">{x.productName}</td><td className="text-white/45">{x.category}</td><td>{segmentMeta[x.segment].label}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{money(x.markup)}</td><td className="text-right">{money(x.unitMarkup)}</td><td className="text-right">{pct(x.markupPercent)}</td><td className="text-center font-black">{x.abcRevenue}</td><td className="text-center font-black">{x.abcQuantity}</td><td className="text-center font-black">{x.abcMarkup}</td></tr>)}</tbody></table></div></Panel>
 <footer className="mt-7 flex flex-col justify-between gap-3 text-xs text-white/30 md:flex-row"><span>Snapshot: {new Date(data.updatedAt).toLocaleString('uk-UA')}</span><span className="flex items-center gap-2"><BarChart3 size={14}/> MARMOO Menu Intelligence v1</span></footer></div></div>
}
