import React,{useEffect,useMemo,useState}from'react';
import{BarChart3,RefreshCw,Star,Trophy,Puzzle,Dog,UtensilsCrossed,Search,GitFork}from'lucide-react';
import{Payload,buildRange,inRange,money,num,pct,fullDate,shortDate}from'./sales/data';
import{cleanProductRows,normalizeProductName}from'./sales/semantic';
import{useFilters}from'./context/FilterContext';
import DrilldownDrawer from'./components/DrilldownDrawer';

type MenuRow={productName:string;category:string;quantity:number;revenue:number;markup:number;cost:number;avgPrice:number;unitMarkup:number;markupPercent:number;revenueShare:number;quantityShare:number;abcRevenue:'A'|'B'|'C';abcQuantity:'A'|'B'|'C';abcMarkup:'A'|'B'|'C';segment:'Star'|'Plow Horse'|'Puzzle'|'Dog'};
type BasketPair={itemA:string;itemB:string;coOccurrence:number;support:number;confidenceAtoB:number;confidenceBtoA:number;lift:number};
type IntelligencePayload={basketPairs?:BasketPair[]};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const INTELLIGENCE_URL=`${import.meta.env.BASE_URL||'/'}intelligence-data.json`;
const segmentMeta={Star:{label:'Зірки',icon:Star,helper:'Високий попит · висока націнка',className:'border-emerald-200/20 bg-emerald-100/10 text-emerald-100'},'Plow Horse':{label:'Робочі конячки',icon:Trophy,helper:'Високий попит · нижча націнка',className:'border-amber-200/20 bg-amber-100/10 text-amber-100'},Puzzle:{label:'Загадки',icon:Puzzle,helper:'Низький попит · висока націнка',className:'border-sky-200/20 bg-sky-100/10 text-sky-100'},Dog:{label:'Собаки',icon:Dog,helper:'Низький попит · нижча націнка',className:'border-rose-200/20 bg-rose-100/10 text-rose-100'}}as const;

function classifyABC<T extends MenuRow>(rows:T[],field:'revenue'|'quantity'|'markup'){const sorted=[...rows].sort((a,b)=>b[field]-a[field]);const total=sorted.reduce((s,x)=>s+x[field],0);let acc=0;const map=new Map<string,'A'|'B'|'C'>();sorted.forEach(x=>{acc+=x[field];const share=total?acc/total:1;map.set(x.productName,share<=.8?'A':share<=.95?'B':'C')});return map}
function median(values:number[]){if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-xl font-black text-[#d8f4f2] md:text-2xl">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}

export default function MenuDashboard(){
 const{filters,setFilters,toggleCategory,toggleProduct}=useFilters();
 const[data,setData]=useState<Payload|null>(null),[intel,setIntel]=useState<IntelligencePayload|null>(null),[loading,setLoading]=useState(true),[segment,setSegment]=useState<'all'|MenuRow['segment']>('all'),[drawer,setDrawer]=useState<MenuRow|null>(null);
 const load=async()=>{setLoading(true);try{const[r1,r2]=await Promise.all([fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'}),fetch(`${INTELLIGENCE_URL}?_=${Date.now()}`,{cache:'no-store'})]);const p=await r1.json()as Payload;if(Number(p.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(p);if(r2.ok)setIntel(await r2.json()as IntelligencePayload)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const rows=useMemo<MenuRow[]>(()=>{if(!data)return[];let source=data.productsDaily.filter(x=>inRange(x.date,range.from,range.to));if(filters.selectedDates.length)source=source.filter(x=>filters.selectedDates.includes(String(x.date)));if(filters.selectedCategories.length)source=source.filter(x=>filters.selectedCategories.includes(String(x.category||'Без категорії')));const prepared=filters.hideServiceItems?cleanProductRows(source as any):source;const m=new Map<string,any>();prepared.forEach((x:any)=>{const name=filters.normalizeProducts?normalizeProductName(x.productName):String(x.productName||'').trim();if(filters.selectedProducts.length&&!filters.selectedProducts.includes(name))return;const key=name.toLowerCase();const cur=m.get(key)||{productName:name,category:x.category||'Без категорії',quantity:0,revenue:0,markup:0};cur.quantity+=Number(x.quantity)||0;cur.revenue+=Number(x.revenue)||0;cur.markup+=Number(x.markup)||0;if((!cur.category||cur.category==='Без категорії')&&x.category)cur.category=x.category;m.set(key,cur)});const base=[...m.values()].filter(x=>x.quantity>0&&x.revenue>0).map(x=>({...x,cost:x.revenue-x.markup,avgPrice:x.revenue/x.quantity,unitMarkup:x.markup/x.quantity,markupPercent:x.revenue?x.markup/x.revenue*100:0,revenueShare:0,quantityShare:0,abcRevenue:'C',abcQuantity:'C',abcMarkup:'C',segment:'Dog'}));const revTotal=base.reduce((s,x)=>s+x.revenue,0),qtyTotal=base.reduce((s,x)=>s+x.quantity,0),marginMedian=median(base.map(x=>x.unitMarkup));const popularityThreshold=base.length?(.7/base.length)*100:0;const abcR=classifyABC(base as MenuRow[],'revenue'),abcQ=classifyABC(base as MenuRow[],'quantity'),abcM=classifyABC(base as MenuRow[],'markup');return base.map(x=>{const quantityShare=qtyTotal?x.quantity/qtyTotal*100:0,popular=quantityShare>=popularityThreshold,profitable=x.unitMarkup>=marginMedian;return{...x,revenueShare:revTotal?x.revenue/revTotal*100:0,quantityShare,abcRevenue:abcR.get(x.productName)||'C',abcQuantity:abcQ.get(x.productName)||'C',abcMarkup:abcM.get(x.productName)||'C',segment:popular?(profitable?'Star':'Plow Horse'):(profitable?'Puzzle':'Dog')}}).sort((a,b)=>b.revenue-a.revenue) as MenuRow[]},[data,range,filters.selectedDates,filters.selectedCategories,filters.selectedProducts,filters.normalizeProducts,filters.hideServiceItems]);
 const categories=useMemo(()=>data?[...new Set(data.productsDaily.map(x=>String(x.category||'Без категорії')))].sort():[],[data]);
 const filtered=useMemo(()=>rows.filter(x=>(segment==='all'||x.segment===segment)&&(!filters.searchQuery||x.productName.toLowerCase().includes(filters.searchQuery.toLowerCase())||x.category.toLowerCase().includes(filters.searchQuery.toLowerCase()))),[rows,segment,filters.searchQuery]);
 const basketPairs=useMemo(()=>{const valid=new Set(rows.map(x=>x.productName.toLowerCase()));return(intel?.basketPairs||[]).filter(x=>valid.has(x.itemA.toLowerCase())||valid.has(x.itemB.toLowerCase())).filter(x=>x.coOccurrence>=3&&x.lift>1).sort((a,b)=>b.coOccurrence-a.coOccurrence||b.lift-a.lift).slice(0,12)},[intel,rows]);
 const totalRevenue=rows.reduce((s,x)=>s+x.revenue,0),totalMarkup=rows.reduce((s,x)=>s+x.markup,0),totalQty=rows.reduce((s,x)=>s+x.quantity,0);
 const openProduct=(row:MenuRow)=>setDrawer(row);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-6 md:px-8 md:py-9">
 <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex items-center gap-3 text-[#cfeeed]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06]"><UtensilsCrossed size={23}/></div><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">АНАЛІТИКА МЕНЮ</p><h1 className="text-4xl font-black md:text-5xl">Страви</h1></div></div><p className="mt-4 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
 <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(segmentMeta).map(([key,meta])=>{const count=rows.filter(x=>x.segment===key).length,Icon=meta.icon;return <button key={key} onClick={()=>setSegment(segment===key?'all':key as MenuRow['segment'])} className={`rounded-[24px] border p-5 text-left ${meta.className} ${segment===key?'ring-2 ring-[#cfeeed]':''}`}><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] opacity-65">{meta.label}</p><div className="mt-2 text-3xl font-black">{count}</div></div><Icon size={28}/></div><p className="mt-3 text-xs opacity-60">{meta.helper}</p></button>})}</div>
 <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Оборот меню" value={money(totalRevenue)}/><Kpi label="Продано" value={`${num(totalQty)} од.`}/><Kpi label="Націнка" value={money(totalMarkup)}/><Kpi label="Позицій у аналізі" value={num(rows.length)}/></div>
 <Panel title="Фільтр страв" subtitle="Пошук і вибір категорій працюють разом із глобальними фільтрами"><div className="grid gap-4 xl:grid-cols-[1fr_2fr]"><label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/10 px-4 py-3"><Search size={18} className="text-white/40"/><input value={filters.searchQuery} onChange={e=>setFilters(p=>({...p,searchQuery:e.target.value}))} placeholder="Назва страви або категорія" className="w-full bg-transparent text-sm outline-none placeholder:text-white/30"/></label><div className="flex gap-2 overflow-x-auto">{categories.map(category=><button key={category} onClick={()=>toggleCategory(category)} className={`min-w-max rounded-xl border px-3 py-2 text-xs font-black ${filters.selectedCategories.includes(category)?'border-[#cfeeed] bg-[#cfeeed] text-[#531027]':'border-white/10 bg-white/[.04] text-white/60'}`}>{category}</button>)}</div></div></Panel>
 <Panel title="Матриця Menu Engineering" subtitle="Клік по страві відкриває деталі; фільтр застосовується окремо" className="mt-5"><div className="grid gap-4 lg:grid-cols-2">{Object.entries(segmentMeta).map(([key,meta])=>{const list=rows.filter(x=>x.segment===key).slice(0,8),Icon=meta.icon;return <div key={key} className={`rounded-2xl border p-4 ${meta.className}`}><div className="mb-3 flex items-center justify-between"><div><h3 className="font-black">{meta.label}</h3><p className="text-xs opacity-55">{meta.helper}</p></div><Icon size={22}/></div><div className="space-y-2">{list.map(x=>{const active=filters.selectedProducts.includes(x.productName);return <button type="button" key={x.productName} onClick={()=>openProduct(x)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-left text-sm transition ${active?'bg-[#cfeeed]/15 ring-1 ring-[#cfeeed]/50':'bg-black/10 hover:bg-white/[.06]'}`}><span className="max-w-[65%] font-semibold">{x.productName}</span><span className="text-right"><b>{num(x.quantity)} од.</b><br/><span className="text-xs opacity-55">{money(x.unitMarkup)}/од.</span></span></button>})}</div></div>})}</div></Panel>
 <Panel title="Комбінації для крос-продажу" subtitle="Клік по назві страви фільтрує меню за цією позицією" className="mt-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{basketPairs.length?basketPairs.map(x=><div key={`${x.itemA}-${x.itemB}`} className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-start gap-3"><GitFork size={18} className="mt-1 text-[#cfeeed]"/><div><button type="button" onClick={()=>toggleProduct(x.itemA)} className={`rounded-lg px-2 py-1 text-left font-black ${filters.selectedProducts.includes(x.itemA)?'bg-[#cfeeed]/15 ring-1 ring-[#cfeeed]/45':'hover:bg-white/[.05]'}`}>{x.itemA}</button><div className="my-1 text-xs text-white/35">разом із</div><button type="button" onClick={()=>toggleProduct(x.itemB)} className={`rounded-lg px-2 py-1 text-left font-black ${filters.selectedProducts.includes(x.itemB)?'bg-[#cfeeed]/15 ring-1 ring-[#cfeeed]/45':'hover:bg-white/[.05]'}`}>{x.itemB}</button><div className="mt-3 flex gap-3 text-xs text-white/50"><span>{num(x.coOccurrence)} чеків</span><span>Lift {x.lift.toFixed(2)}</span><span>Support {pct(x.support*100)}</span></div></div></div></div>):<div className="text-sm text-white/45">Дані комбінацій ще не завантажені.</div>}</div></Panel>
 <Panel title="Повний рейтинг страв" subtitle={segment==='all'?range.label:`${range.label} · ${segmentMeta[segment].label}`} className="mt-5"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Страва</th><th>Категорія</th><th>Сегмент</th><th className="text-right">Кількість</th><th className="text-right">Частка к-сті</th><th className="text-right">Оборот</th><th className="text-right">Націнка</th><th className="text-right">Націнка/од.</th><th className="text-center">ABC оборот</th><th className="text-center">ABC к-сть</th><th className="text-center">ABC націнка</th></tr></thead><tbody>{filtered.map((x,i)=>{const active=filters.selectedProducts.includes(x.productName);return <tr key={x.productName} onClick={()=>openProduct(x)} className={`cursor-pointer border-b border-white/[.07] transition ${active?'bg-[#cfeeed]/12':'hover:bg-white/[.04]'}`}><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-semibold">{x.productName}</td><td className="text-white/45">{x.category}</td><td>{segmentMeta[x.segment].label}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right">{pct(x.quantityShare)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{money(x.markup)}</td><td className="text-right">{money(x.unitMarkup)}</td><td className="text-center font-black">{x.abcRevenue}</td><td className="text-center font-black">{x.abcQuantity}</td><td className="text-center font-black">{x.abcMarkup}</td></tr>})}</tbody></table></div></Panel>
 <footer className="mt-7 flex flex-col justify-between gap-3 text-xs text-white/30 md:flex-row"><span>Snapshot: {new Date(data.updatedAt).toLocaleString('uk-UA')}</span><span className="flex items-center gap-2"><BarChart3 size={14}/> MARMOO Menu Intelligence v2</span></footer></div><DrilldownDrawer open={!!drawer} eyebrow="СТРАВА" title={drawer?.productName||''} subtitle={drawer?`${drawer.category} · ${segmentMeta[drawer.segment].label}`:undefined} metrics={drawer?[{label:'Оборот',value:money(drawer.revenue)},{label:'Частка обороту',value:pct(drawer.revenueShare)},{label:'Продано',value:`${num(drawer.quantity)} од.`},{label:'Середня ціна',value:money(drawer.avgPrice)},{label:'Націнка',value:money(drawer.markup)},{label:'Націнка/од.',value:money(drawer.unitMarkup)},{label:'Націнка %',value:pct(drawer.markupPercent)},{label:'ABC',value:`${drawer.abcRevenue}/${drawer.abcQuantity}/${drawer.abcMarkup}`,hint:'Оборот / кількість / націнка'}]:[]} actionLabel="Застосувати як фільтр" onAction={drawer?()=>{toggleProduct(drawer.productName);setDrawer(null)}:undefined} onClose={()=>setDrawer(null)}/></div>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-black uppercase text-white/45">{label}</p><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div></div>}
