import React,{useEffect,useMemo,useState}from'react';
import{Activity,BarChart3,CalendarDays,Clock3,CreditCard,Flame,Layers3,RefreshCw,ShoppingBasket,Store,TrendingDown,TrendingUp,Truck,Users,Zap,AlertTriangle}from'lucide-react';
import{Area,Bar,CartesianGrid,ComposedChart,Line,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import Heatmap from'./sales/Heatmap';
import{Payload,PeriodKey,PERIODS,buildRange,inRange,aggregate,change,money,num,pct,parseDate,shortDate,fullDate}from'./sales/data';

type ChartMetric='revenue'|'orders'|'markup'|'averageCheck';type ProductMetric='revenue'|'quantity'|'markup';
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const chartOptions:[ChartMetric,string,string][]=[['revenue','Оборот','#cfeeed'],['orders','Чеки','#f5c8da'],['markup','Націнка','#ffd9a8'],['averageCheck','Середній чек','#b9a7ff']];
const tooltipStyle={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};

function Delta({value,label}:{value:number|null;label:string}){if(value===null)return <span className="text-[11px] font-semibold opacity-60">{label}</span>;const up=value>=0;return <div className="flex flex-col items-end gap-1"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1.5 text-[13px] font-black ${up?'bg-emerald-100 text-emerald-800':'bg-rose-100 text-rose-800'}`}>{up?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {up?'+':''}{value.toFixed(1)}%</span><span className="max-w-[130px] text-right text-[11px] font-semibold leading-tight opacity-75">{label}</span></div>}
function Card({label,value,helper,delta,comparison,icon:Icon,tone='light'}:{label:string;value:string;helper:string;delta?:number|null;comparison:string;icon:React.ElementType;tone?:'light'|'mint'|'dark'}){const c=tone==='mint'?'bg-[#cfeeed] text-[#531027]':tone==='dark'?'bg-white/[.06] text-white border-white/10':'bg-[#f6eee8] text-[#5b0b25]';return <div className={`rounded-[26px] border border-white/60 p-5 ${c}`}><div className="flex justify-between"><p className="text-[10px] font-black uppercase tracking-[.18em] opacity-65">{label}</p><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/35 bg-white/35"><Icon size={18}/></div></div><div className="mt-3 text-[32px] font-black leading-none">{value}</div><div className="mt-5 flex min-h-[58px] items-start justify-between gap-3"><span className="pt-1 text-xs font-semibold opacity-70">{helper}</span>{delta!==undefined&&<Delta value={delta} label={comparison}/>}</div></div>}
function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-xl font-black text-[#d8f4f2] md:text-2xl">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}
function StatBox({label,value,sub,tone='mint'}:{label:string;value:string;sub:string;tone?:'mint'|'rose'}){return <div className={`rounded-2xl border p-4 ${tone==='mint'?'border-emerald-200/20 bg-emerald-100/10':'border-rose-200/20 bg-rose-100/10'}`}><p className="text-[10px] uppercase tracking-[.16em] text-white/45">{label}</p><div className="mt-2 text-2xl font-black text-[#d8f4f2]">{value}</div><p className="mt-1 text-xs text-white/45">{sub}</p></div>}

export default function SalesDashboardV3(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<PeriodKey>('current_month'),[metrics,setMetrics]=useState<ChartMetric[]>(['revenue','orders','markup']),[productMetric,setProductMetric]=useState<ProductMetric>('revenue');
 const load=async()=>{setLoading(true);try{const r=await fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json()as Payload;if(p.schemaVersion!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const today=useMemo(()=>new Date(),[]),range=useMemo(()=>buildRange(period,today),[period,today]);
 const daily=useMemo(()=>data?data.daily.filter(x=>inRange(x.date,range.from,range.to)):[],[data,range]);
 const prevDaily=useMemo(()=>data&&period!=='all'?data.daily.filter(x=>inRange(x.date,range.comparisonFrom,range.comparisonTo)):[],[data,period,range]);
 const current=useMemo(()=>aggregate(daily),[daily]),previous=useMemo(()=>aggregate(prevDaily),[prevDaily]);
 const channels=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.channelsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const v=m.get(x.channel)||{channel:x.channel,revenue:0,orders:0,markup:0};v.revenue+=x.revenue;v.orders+=x.orders;v.markup+=x.markup;m.set(x.channel,v)});return[...m.values()].map(x=>({...x,markupPercent:x.revenue?x.markup/x.revenue*100:0})).sort((a,b)=>b.revenue-a.revenue)},[data,range]);
 const hourly=useMemo(()=>{if(!data)return[];const m=new Map<number,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const v=m.get(x.hour)||{hour:x.hour,revenue:0,orders:0,markup:0};v.revenue+=x.revenue;v.orders+=x.orders;v.markup+=x.markup;m.set(x.hour,v)});return[...m.values()].map(x=>({...x,averageCheck:x.orders?x.revenue/x.orders:0})).sort((a,b)=>a.hour-b.hour)},[data,range]);
 const allProducts=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.productsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const k=x.productCode+'|'+x.productName,v=m.get(k)||{productCode:x.productCode,productName:x.productName,category:x.category,quantity:0,revenue:0,markup:0};v.quantity+=x.quantity;v.revenue+=x.revenue;v.markup+=x.markup;m.set(k,v)});return[...m.values()].map(x=>({...x,markupPercent:x.revenue?x.markup/x.revenue*100:0}))},[data,range]);
 const products=useMemo(()=>[...allProducts].sort((a,b)=>b[productMetric]-a[productMetric]).slice(0,10),[allProducts,productMetric]);
 const antiProducts=useMemo(()=>[...allProducts].filter(x=>x.quantity>0).sort((a,b)=>a[productMetric]-b[productMetric]).slice(0,5),[allProducts,productMetric]);
 const categories=useMemo(()=>{const m=new Map<string,any>();allProducts.forEach(x=>{const k=x.category||'Без категорії',v=m.get(k)||{category:k,quantity:0,revenue:0,markup:0};v.quantity+=x.quantity;v.revenue+=x.revenue;v.markup+=x.markup;m.set(k,v)});const total=[...m.values()].reduce((s,x)=>s+x.revenue,0);return[...m.values()].map(x=>({...x,share:total?x.revenue/total*100:0,markupPercent:x.revenue?x.markup/x.revenue*100:0})).sort((a,b)=>b.revenue-a.revenue)},[allProducts]);
 const heat=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const weekday=parseDate(x.date).getDay()||7,k=weekday+'|'+x.hour,v=m.get(k)||{weekday,hour:x.hour,revenue:0,orders:0};v.revenue+=x.revenue;v.orders+=x.orders;m.set(k,v)});return[...m.values()]},[data,range]);
 const rankedHours=useMemo(()=>[...hourly].sort((a,b)=>b.revenue-a.revenue),[hourly]);const bestHours=rankedHours.slice(0,3),weakHours=[...rankedHours].reverse().slice(0,3);
 const channelTotal=channels.reduce((s,x)=>s+x.revenue,0),soft=data?.milestones?.softOpening||'2026-06-18',grand=data?.milestones?.grandOpening||'2026-06-26';
 const deltas={revenue:period==='all'?null:change(current.revenue,previous.revenue),orders:period==='all'?null:change(current.orders,previous.orders),averageCheck:period==='all'?null:change(current.averageCheck,previous.averageCheck),markup:period==='all'?null:change(current.markup,previous.markup),cost:period==='all'?null:change(current.cost,previous.cost)};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 const bestDay=daily.length?[...daily].sort((a,b)=>b.revenue-a.revenue)[0]:null,bestChannel=channels[0],bestCategory=categories[0];
 const signals=[deltas.revenue===null?null:`Оборот ${deltas.revenue>=0?'виріс':'знизився'} на ${Math.abs(deltas.revenue).toFixed(1)}% ${range.comparisonLabel}.`,bestDay?`Найкращий день — ${shortDate(bestDay.date)}: ${money(bestDay.revenue)}.`:null,bestHours[0]?`Найсильніша година — ${bestHours[0].hour}:00, ${money(bestHours[0].revenue)}.`:null,weakHours[0]?`Найслабша година — ${weakHours[0].hour}:00, ${money(weakHours[0].revenue)}.`:null,bestChannel?`Найбільший канал — ${bestChannel.channel}, частка ${(bestChannel.revenue/channelTotal*100).toFixed(1)}%.`:null,bestCategory?`Найсильніша категорія — ${bestCategory.category}, ${money(bestCategory.revenue)}.`:null].filter(Boolean)as string[];
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-6 md:px-8 md:py-9">
 <header className="mb-5 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="flex items-center gap-3 text-[#cfeeed]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06]"><BarChart3 size={23}/></div><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">MARMOO Intelligence</p><h1 className="text-4xl font-black md:text-5xl">Sales BI</h1></div></div><p className="mt-4 text-sm text-white/50">Олімпійська · Велика Васильківська, 57/3</p><p className="mt-1 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити snapshot</button></header>
 <div className="mb-6 overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{PERIODS.map(p=><button key={p.key} onClick={()=>setPeriod(p.key)} className={`rounded-xl border px-4 py-2.5 text-sm font-bold ${period===p.key?'border-[#cfeeed] bg-[#cfeeed] text-[#5b0b25]':'border-white/10 bg-white/[.05] text-white/65'}`}>{p.label}</button>)}</div></div>
 <div className="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card label="Оборот" value={money(current.revenue)} helper={range.label} delta={deltas.revenue} comparison={range.comparisonLabel} icon={TrendingUp} tone="mint"/><Card label="Чеки" value={num(current.orders)} helper="завершені" delta={deltas.orders} comparison={range.comparisonLabel} icon={CreditCard}/><Card label="Середній чек" value={money(current.averageCheck)} helper="оборот / чеки" delta={deltas.averageCheck} comparison={range.comparisonLabel} icon={ShoppingBasket}/><Card label="Націнка" value={money(current.markup)} helper={pct(current.markupPercent)} delta={deltas.markup} comparison={range.comparisonLabel} icon={Flame} tone="mint"/><Card label="Собівартість" value={money(current.cost)} helper="розрахункова" delta={deltas.cost} comparison={range.comparisonLabel} icon={Layers3}/><Card label="Клієнти" value={num(data.summary.identifiedCustomers)} helper={`${num(data.summary.identifiedOrders)} чеків`} comparison="весь період" icon={Users} tone="dark"/></div>
 <div className="grid grid-cols-1 gap-5 xl:grid-cols-12">
 <Panel title="Динаміка продажів" subtitle={`${range.label} · обери показники`} className="xl:col-span-8"><div className="mb-4 flex flex-wrap gap-2">{chartOptions.map(([k,l,c])=>{const active=metrics.includes(k);return <button key={k} onClick={()=>setMetrics(v=>active?(v.length>1?v.filter(x=>x!==k):v):[...v,k])} className={`rounded-xl border px-3 py-2 text-xs font-black ${active?'border-white/30 bg-white/10':'border-white/10 text-white/40'}`}><span className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{background:c}}/>{l}</button>})}</div><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={daily}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="date" tickFormatter={shortDate} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis yAxisId="m" tickFormatter={v=>`${Math.round(v/1000)}k`} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis yAxisId="o" orientation="right" hide/><Tooltip contentStyle={tooltipStyle} labelFormatter={shortDate} formatter={(v:number,k:string)=>k==='orders'?num(v):money(v)}/>{daily.some(x=>x.date===soft)&&<ReferenceLine x={soft} stroke="#fff" strokeDasharray="4 5" label={{value:'Soft opening',fill:'#fff',fontSize:10}}/>}{daily.some(x=>x.date===grand)&&<ReferenceLine x={grand} stroke="#ffd9a8" strokeDasharray="4 5" label={{value:'Офіційне відкриття',fill:'#ffd9a8',fontSize:10}}/>}{metrics.includes('revenue')&&<Area yAxisId="m" type="monotone" dataKey="revenue" stroke="#cfeeed" fill="#cfeeed" fillOpacity={.12} strokeWidth={3}/>} {metrics.includes('markup')&&<Line yAxisId="m" type="monotone" dataKey="markup" stroke="#ffd9a8" strokeWidth={2.5} dot={false}/>} {metrics.includes('averageCheck')&&<Line yAxisId="m" type="monotone" dataKey="averageCheck" stroke="#b9a7ff" strokeWidth={2.5} dot={false}/>} {metrics.includes('orders')&&<Bar yAxisId="o" dataKey="orders" fill="#f5c8da" opacity={.55}/>}</ComposedChart></ResponsiveContainer></div></Panel>
 <Panel title="Керівницькі сигнали" subtitle={range.comparisonLabel} className="xl:col-span-4"><div className="space-y-3">{signals.map((x,i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm text-white/75"><b className="mr-2 text-[#cfeeed]">{i+1}.</b>{x}</div>)}</div></Panel>
 <Panel title="Сильні та слабкі години" subtitle={range.label} className="xl:col-span-12"><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-6">{bestHours.map((x,i)=><StatBox key={'b'+x.hour} label={`Топ ${i+1}`} value={`${x.hour}:00`} sub={`${money(x.revenue)} · ${num(x.orders)} чеків`} />)}{weakHours.map((x,i)=><StatBox key={'w'+x.hour} label={`Слабка ${i+1}`} value={`${x.hour}:00`} sub={`${money(x.revenue)} · ${num(x.orders)} чеків`} tone="rose"/>)}</div></Panel>
 <Panel title="Канали продажів" subtitle={`${range.label} · частка обороту`} className="xl:col-span-5"><div className="space-y-5">{channels.map(x=>{const share=channelTotal?x.revenue/channelTotal*100:0;return <div key={x.channel}><div className="mb-2 flex justify-between"><div className="flex items-center gap-2">{x.channel==='Зал'?<Store size={15}/>:<Truck size={15}/>}<b>{x.channel}</b></div><div className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><div className="text-xs text-white/45">{share.toFixed(1)}% · {num(x.orders)} чеків</div></div></div><div className="h-2.5 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-[#cfeeed]" style={{width:`${share}%`}}/></div></div>})}</div></Panel>
 <Panel title="Теплова карта попиту" subtitle={`${range.label} · день × година`} className="xl:col-span-7"><Heatmap cells={heat}/></Panel>
 <Panel title="Категорії меню" subtitle={`${range.label} · оборот і націнка`} className="xl:col-span-7"><div className="space-y-4">{categories.slice(0,8).map(x=><div key={x.category}><div className="mb-2 flex items-end justify-between"><div><b>{x.category}</b><div className="text-xs text-white/40">{num(x.quantity)} од. · націнка {pct(x.markupPercent)}</div></div><div className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><div className="text-xs text-white/40">{x.share.toFixed(1)}%</div></div></div><div className="h-2 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-[#ffd9a8]" style={{width:`${x.share}%`}}/></div></div>)}</div></Panel>
 <Panel title="Анти-топ страв" subtitle={`${range.label} · найнижчі значення`} className="xl:col-span-5"><div className="space-y-3">{antiProducts.map((x,i)=><div key={x.productCode+'a'} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.035] p-4"><div><div className="font-bold">{i+1}. {x.productName}</div><div className="text-xs text-white/40">{x.category}</div></div><div className="text-right"><div className="font-black text-rose-200">{productMetric==='quantity'?num(x.quantity):money(x[productMetric])}</div><div className="text-xs text-white/40">{num(x.quantity)} од.</div></div></div>)}</div></Panel>
 <Panel title="Топ страв" subtitle={range.label} className="xl:col-span-12"><div className="mb-4 flex gap-2">{([['revenue','Оборот'],['quantity','Кількість'],['markup','Націнка']]as[ProductMetric,string][]).map(([k,l])=><button key={k} onClick={()=>setProductMetric(k)} className={`rounded-xl border px-3 py-2 text-xs font-black ${productMetric===k?'bg-[#cfeeed] text-[#5b0b25]':'border-white/10 text-white/50'}`}>{l}</button>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.14em] text-white/35"><th className="pb-3">#</th><th>Страва</th><th>Категорія</th><th className="text-right">Кількість</th><th className="text-right">Оборот</th><th className="text-right">Націнка</th></tr></thead><tbody>{products.map((x,i)=><tr key={x.productCode+i} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-semibold">{x.productName}</td><td className="text-white/45">{x.category}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{money(x.markup)}</td></tr>)}</tbody></table></div></Panel>
 </div><footer className="mt-7 flex flex-col justify-between gap-3 text-xs text-white/30 md:flex-row"><span className="flex items-center gap-2"><CalendarDays size={14}/> Snapshot: {new Date(data.updatedAt).toLocaleString('uk-UA')}</span><span className="flex items-center gap-2"><Clock3 size={14}/> Дані: {shortDate(data.period.from)} — {shortDate(data.period.to)}</span><span className="flex items-center gap-2"><Activity size={14}/> MARMOO Sales Intelligence v6</span></footer></div></div>
}
