import React,{useEffect,useMemo,useState}from'react';
import{Activity,BarChart3,CalendarDays,Clock3,CreditCard,Flame,Layers3,RefreshCw,ShoppingBasket,Store,TrendingDown,TrendingUp,Truck,Users}from'lucide-react';
import{Area,Bar,CartesianGrid,ComposedChart,Line,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import Heatmap from'./sales/Heatmap';
import{Payload,PeriodKey,PERIODS,buildRange,inRange,aggregate,change,money,num,pct,parseDate,shortDate,fullDate}from'./sales/data';

type ChartMetric='revenue'|'orders'|'markup'|'averageCheck';type ProductMetric='revenue'|'quantity'|'markup';
const URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const charts:[ChartMetric,string,string][]=[['revenue','Оборот','#cfeeed'],['orders','Чеки','#f5c8da'],['markup','Націнка','#ffd9a8'],['averageCheck','Середній чек','#b9a7ff']];
const tip={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};

function Delta({v,label}:{v:number|null;label:string}){if(v===null)return <span className="text-[11px] font-semibold opacity-60">{label}</span>;const up=v>=0;return <div className="flex flex-col items-end gap-1"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1.5 text-[13px] font-black ${up?'bg-emerald-100 text-emerald-800':'bg-rose-100 text-rose-800'}`}>{up?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {up?'+':''}{v.toFixed(1)}%</span><span className="max-w-[130px] text-right text-[11px] font-semibold leading-tight opacity-75">{label}</span></div>}
function Card({label,value,helper,d,comparison,icon:Icon,tone='light'}:{label:string;value:string;helper:string;d?:number|null;comparison:string;icon:React.ElementType;tone?:'light'|'mint'|'dark'}){const c=tone==='mint'?'bg-[#cfeeed] text-[#531027]':tone==='dark'?'bg-white/[.06] text-white border-white/10':'bg-[#f6eee8] text-[#5b0b25]';return <div className={`rounded-[26px] border border-white/60 p-5 ${c}`}><div className="flex justify-between"><p className="text-[10px] font-black uppercase tracking-[.18em] opacity-65">{label}</p><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/35 bg-white/35"><Icon size={18}/></div></div><div className="mt-3 text-[32px] font-black leading-none">{value}</div><div className="mt-5 flex min-h-[58px] items-start justify-between gap-3"><span className="pt-1 text-xs font-semibold opacity-70">{helper}</span>{d!==undefined&&<Delta v={d} label={comparison}/>}</div></div>}
function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-xl font-black text-[#d8f4f2] md:text-2xl">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}

export default function SalesDashboardV2(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[period,setPeriod]=useState<PeriodKey>('current_month'),[metrics,setMetrics]=useState<ChartMetric[]>(['revenue','orders','markup']),[productMetric,setProductMetric]=useState<ProductMetric>('revenue');
 const load=async()=>{setLoading(true);try{const r=await fetch(`${URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json()as Payload;if(p.schemaVersion!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const today=useMemo(()=>new Date(),[]),range=useMemo(()=>buildRange(period,today),[period,today]);
 const daily=useMemo(()=>data?data.daily.filter(x=>inRange(x.date,range.from,range.to)):[],[data,range]);const prevDaily=useMemo(()=>data&&period!=='all'?data.daily.filter(x=>inRange(x.date,range.comparisonFrom,range.comparisonTo)):[],[data,period,range]);const cur=useMemo(()=>aggregate(daily),[daily]),prev=useMemo(()=>aggregate(prevDaily),[prevDaily]);
 const channels=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.channelsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const v=m.get(x.channel)||{...x,revenue:0,orders:0,markup:0};v.revenue+=x.revenue;v.orders+=x.orders;v.markup+=x.markup;m.set(x.channel,v)});return[...m.values()].map(x=>({...x,markupPercent:x.revenue?x.markup/x.revenue*100:0})).sort((a,b)=>b.revenue-a.revenue)},[data,range]);
 const hourly=useMemo(()=>{if(!data)return[];const m=new Map<number,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const v=m.get(x.hour)||{...x,revenue:0,orders:0,markup:0};v.revenue+=x.revenue;v.orders+=x.orders;v.markup+=x.markup;m.set(x.hour,v)});return[...m.values()].sort((a,b)=>a.hour-b.hour)},[data,range]);
 const products=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.productsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const k=x.productCode+'|'+x.productName,v=m.get(k)||{...x,quantity:0,revenue:0,markup:0};v.quantity+=x.quantity;v.revenue+=x.revenue;v.markup+=x.markup;m.set(k,v)});return[...m.values()].map(x=>({...x,markupPercent:x.revenue?x.markup/x.revenue*100:0})).sort((a,b)=>b[productMetric]-a[productMetric]).slice(0,10)},[data,range,productMetric]);
 const heat=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const weekday=parseDate(x.date).getDay()||7,k=weekday+'|'+x.hour,v=m.get(k)||{weekday,hour:x.hour,revenue:0,orders:0};v.revenue+=x.revenue;v.orders+=x.orders;m.set(k,v)});return[...m.values()]},[data,range]);
 const peak=[...hourly].sort((a,b)=>b.revenue-a.revenue)[0],channelTotal=channels.reduce((s,x)=>s+x.revenue,0),soft=data?.milestones?.softOpening||'2026-06-18',grand=data?.milestones?.grandOpening||'2026-06-26';
 const deltas={revenue:period==='all'?null:change(cur.revenue,prev.revenue),orders:period==='all'?null:change(cur.orders,prev.orders),averageCheck:period==='all'?null:change(cur.averageCheck,prev.averageCheck),markup:period==='all'?null:change(cur.markup,prev.markup),cost:period==='all'?null:change(cur.cost,prev.cost)};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 const insights=[deltas.revenue===null?null:`Оборот ${deltas.revenue>=0?'виріс':'знизився'} на ${Math.abs(deltas.revenue).toFixed(1)}% ${range.comparisonLabel}.`,daily[0]?`Найкращий день — ${shortDate([...daily].sort((a,b)=>b.revenue-a.revenue)[0].date)}.`:null,peak?`Пікова година — ${peak.hour}:00.`:null,channels[0]?`Найбільший канал — ${channels[0].channel}.`:null,products[0]?`Топ-страва — ${products[0].productName}.`:null].filter(Boolean)as string[];
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-6 md:px-8 md:py-9">
 <header className="mb-5 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="flex items-center gap-3 text-[#cfeeed]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/[.06]"><BarChart3 size={23}/></div><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">MARMOO Intelligence</p><h1 className="text-4xl font-black md:text-5xl">Sales BI</h1></div></div><p className="mt-4 text-sm text-white/50">Олімпійська · Велика Васильківська, 57/3</p><p className="mt-1 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити snapshot</button></header>
 <div className="mb-6 overflow-x-auto pb-2"><div className="flex min-w-max gap-2">{PERIODS.map(p=><button key={p.key} onClick={()=>setPeriod(p.key)} className={`rounded-xl border px-4 py-2.5 text-sm font-bold ${period===p.key?'border-[#cfeeed] bg-[#cfeeed] text-[#5b0b25]':'border-white/10 bg-white/[.05] text-white/65'}`}>{p.label}</button>)}</div></div>
 <div className="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card label="Оборот" value={money(cur.revenue)} helper={range.label} d={deltas.revenue} comparison={range.comparisonLabel} icon={TrendingUp} tone="mint"/><Card label="Чеки" value={num(cur.orders)} helper="завершені" d={deltas.orders} comparison={range.comparisonLabel} icon={CreditCard}/><Card label="Середній чек" value={money(cur.averageCheck)} helper="оборот / чеки" d={deltas.averageCheck} comparison={range.comparisonLabel} icon={ShoppingBasket}/><Card label="Націнка" value={money(cur.markup)} helper={pct(cur.markupPercent)} d={deltas.markup} comparison={range.comparisonLabel} icon={Flame} tone="mint"/><Card label="Собівартість" value={money(cur.cost)} helper="розрахункова" d={deltas.cost} comparison={range.comparisonLabel} icon={Layers3}/><Card label="Клієнти" value={num(data.summary.identifiedCustomers)} helper={`${num(data.summary.identifiedOrders)} чеків`} comparison="весь період" icon={Users} tone="dark"/></div>
 <div className="grid grid-cols-1 gap-5 xl:grid-cols-12">
 <Panel title="Динаміка продажів" subtitle={`${range.label} · обери показники`} className="xl:col-span-8"><div className="mb-4 flex flex-wrap gap-2">{charts.map(([k,l,c])=>{const a=metrics.includes(k);return <button key={k} onClick={()=>setMetrics(v=>a?(v.length>1?v.filter(x=>x!==k):v):[...v,k])} className={`rounded-xl border px-3 py-2 text-xs font-black ${a?'border-white/30 bg-white/10':'border-white/10 text-white/40'}`}><span className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{background:c}}/>{l}</button>})}</div><div className="h-[360px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={daily}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="date" tickFormatter={shortDate} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis yAxisId="m" tickFormatter={v=>`${Math.round(v/1000)}k`} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis yAxisId="o" orientation="right" hide/><Tooltip contentStyle={tip} labelFormatter={shortDate} formatter={(v:number,k:string)=>k==='orders'?num(v):money(v)}/>{daily.some(x=>x.date===soft)&&<ReferenceLine x={soft} stroke="#fff" strokeDasharray="4 5" label={{value:'Soft opening',fill:'#fff',fontSize:10}}/>}{daily.some(x=>x.date===grand)&&<ReferenceLine x={grand} stroke="#ffd9a8" strokeDasharray="4 5" label={{value:'Офіційне відкриття',fill:'#ffd9a8',fontSize:10}}/>}{metrics.includes('revenue')&&<Area yAxisId="m" type="monotone" dataKey="revenue" stroke="#cfeeed" fill="#cfeeed" fillOpacity={.12} strokeWidth={3}/>} {metrics.includes('markup')&&<Line yAxisId="m" type="monotone" dataKey="markup" stroke="#ffd9a8" strokeWidth={2.5} dot={false}/>} {metrics.includes('averageCheck')&&<Line yAxisId="m" type="monotone" dataKey="averageCheck" stroke="#b9a7ff" strokeWidth={2.5} dot={false}/>} {metrics.includes('orders')&&<Bar yAxisId="o" dataKey="orders" fill="#f5c8da" opacity={.55}/>}</ComposedChart></ResponsiveContainer></div></Panel>
 <Panel title="Що змінилось" subtitle={range.comparisonLabel} className="xl:col-span-4"><div className="space-y-3">{insights.map((x,i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm text-white/75"><b className="mr-2 text-[#cfeeed]">{i+1}.</b>{x}</div>)}</div></Panel>
 <Panel title="Канали продажів" subtitle={`${range.label} · частка обороту`} className="xl:col-span-5"><div className="space-y-5">{channels.map(x=>{const s=channelTotal?x.revenue/channelTotal*100:0;return <div key={x.channel}><div className="mb-2 flex justify-between"><div className="flex items-center gap-2">{x.channel==='Зал'?<Store size={15}/>:<Truck size={15}/>}<b>{x.channel}</b></div><div className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><div className="text-xs text-white/45">{s.toFixed(1)}% · {num(x.orders)} чеків</div></div></div><div className="h-2.5 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-[#cfeeed]" style={{width:`${s}%`}}/></div></div>})}</div></Panel>
 <Panel title="Години попиту" subtitle={peak?`${range.label} · пік ${peak.hour}:00 · ${money(peak.revenue)}`:range.label} className="xl:col-span-7"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={hourly}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="hour" tickFormatter={v=>`${v}:00`} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tip} formatter={(v:number)=>money(v)}/><Bar dataKey="revenue" fill="#cfeeed" radius={[8,8,0,0]}/></ComposedChart></ResponsiveContainer></div></Panel>
 <Panel title="Теплова карта попиту" subtitle={`${range.label} · день × година`} className="xl:col-span-12"><Heatmap cells={heat}/></Panel>
 <Panel title="Топ страв" subtitle={`${range.label} · рейтинг`} className="xl:col-span-12"><div className="mb-4 flex gap-2">{([['revenue','Оборот'],['quantity','Кількість'],['markup','Націнка']]as[ProductMetric,string][]).map(([k,l])=><button key={k} onClick={()=>setProductMetric(k)} className={`rounded-xl border px-4 py-2 text-sm font-bold ${productMetric===k?'border-[#cfeeed] bg-[#cfeeed] text-[#5b0b25]':'border-white/10 bg-white/[.05] text-white/60'}`}>{l}</button>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase text-white/35"><th className="pb-4">#</th><th className="pb-4">Страва</th><th className="pb-4">Категорія</th><th className="pb-4 text-right">Кількість</th><th className="pb-4 text-right">Оборот</th><th className="pb-4 text-right">Націнка</th><th className="pb-4 text-right">%</th></tr></thead><tbody>{products.map((x,i)=><tr key={x.productCode+i} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="py-4 font-semibold">{x.productName}</td><td className="py-4 text-white/45">{x.category}</td><td className="py-4 text-right">{num(x.quantity)}</td><td className="py-4 text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="py-4 text-right">{money(x.markup)}</td><td className="py-4 text-right">{pct(x.markupPercent)}</td></tr>)}</tbody></table></div></Panel>
 </div><footer className="mt-7 flex flex-col justify-between gap-3 text-xs text-white/30 md:flex-row"><div className="flex items-center gap-2"><CalendarDays size={14}/> Snapshot: {new Date(data.updatedAt).toLocaleString('uk-UA')}</div><div className="flex items-center gap-2"><Clock3 size={14}/> Дані: {shortDate(data.period.from)} — {shortDate(data.period.to)}</div><div className="flex items-center gap-2"><Activity size={14}/> MARMOO Sales Intelligence v5</div></footer></div></div>
}
