import {useCallback,useEffect,useMemo,useState,type ReactNode}from'react';
import{BarChart3,RefreshCw,ReceiptText,ShoppingBasket,TrendingUp,WalletCards}from'lucide-react';
import{Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{Payload,aggregate,buildRange,change,fullDate,inRange,money,num,pct,shortDate}from'./sales/data';
import{cleanProductRows,normalizeProductName}from'./sales/semantic';
import{normalizeChannel}from'./sales/channelNames';
import{useFilters}from'./context/FilterContext';
import Heatmap from'./sales/Heatmap';
import DrilldownDrawer from'./components/DrilldownDrawer';

const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const tooltipStyle={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};
type ChannelRow={channel:string;revenue:number;orders:number;markup:number;share:number;averageCheck:number};
type ProductRow={productName:string;category:string;quantity:number;revenue:number;markup:number};
type DrawerState={type:'date'|'channel'|'category'|'product';title:string;subtitle:string;metrics:{label:string;value:string;hint?:string}[];action:()=>void}|null;

export default function SalesDashboardGlobal(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[drawer,setDrawer]=useState<DrawerState>(null);
 const{filters,toggleChannel,toggleCategory,toggleProduct,toggleDate}=useFilters();
 const closeDrawer=useCallback(()=>setDrawer(null),[]);
 const load=async()=>{setLoading(true);try{const r=await fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json()as Payload;if(Number(p.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const dateAllowed=(value:string)=>!filters.selectedDates.length||filters.selectedDates.includes(value);
 const currentDaily=useMemo(()=>data?data.daily.filter(x=>inRange(x.date,range.from,range.to)&&dateAllowed(x.date)):[],[data,range,filters.selectedDates]);
 const previousDaily=useMemo(()=>data&&filters.compareLFL&&filters.period!=='all'?data.daily.filter(x=>inRange(x.date,range.comparisonFrom,range.comparisonTo)):[],[data,filters.compareLFL,filters.period,range]);
 const current=useMemo(()=>aggregate(currentDaily),[currentDaily]),previous=useMemo(()=>aggregate(previousDaily),[previousDaily]);
 const channels=useMemo<ChannelRow[]>(()=>{if(!data)return[];const m=new Map<string,ChannelRow>();data.channelsDaily.filter(x=>inRange(x.date,range.from,range.to)&&dateAllowed(x.date)).forEach(x=>{const channel=normalizeChannel(x.channel);if(filters.selectedChannels.length&&!filters.selectedChannels.includes(channel))return;const cur=m.get(channel)||{channel,revenue:0,orders:0,markup:0,share:0,averageCheck:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;cur.markup+=Number(x.markup)||0;m.set(channel,cur)});const total=[...m.values()].reduce((s,x)=>s+x.revenue,0);return[...m.values()].map(x=>({...x,share:total?x.revenue/total*100:0,averageCheck:x.orders?x.revenue/x.orders:0})).sort((a,b)=>b.revenue-a.revenue)},[data,range,filters.selectedChannels,filters.selectedDates]);
 const products=useMemo<ProductRow[]>(()=>{if(!data)return[];let source:any[]=data.productsDaily.filter(x=>inRange(x.date,range.from,range.to)&&dateAllowed(x.date));if(filters.hideServiceItems)source=cleanProductRows(source);const map=new Map<string,ProductRow>();source.forEach((x:any)=>{const name=filters.normalizeProducts?normalizeProductName(x.productName):String(x.productName||'').trim();const category=String(x.category||'Без категорії').trim()||'Без категорії';if(filters.selectedCategories.length&&!filters.selectedCategories.includes(category))return;if(filters.selectedProducts.length&&!filters.selectedProducts.includes(name))return;const q=filters.searchQuery.trim().toLowerCase();if(q&&!`${name} ${category}`.toLowerCase().includes(q))return;const key=filters.normalizeProducts?name.toLowerCase():`${x.productCode}|${name}`;const cur=map.get(key)||{productName:name,category,quantity:0,revenue:0,markup:0};cur.quantity+=Number(x.quantity)||0;cur.revenue+=Number(x.revenue)||0;cur.markup+=Number(x.markup)||0;map.set(key,cur)});return[...map.values()].filter(x=>x.quantity>0&&x.revenue>0).sort((a,b)=>b.revenue-a.revenue)},[data,range,filters.hideServiceItems,filters.normalizeProducts,filters.selectedCategories,filters.selectedProducts,filters.searchQuery,filters.selectedDates]);
 const categories=useMemo(()=>{const m=new Map<string,{category:string;revenue:number;quantity:number;markup:number}>();products.forEach(x=>{const cur=m.get(x.category)||{category:x.category,revenue:0,quantity:0,markup:0};cur.revenue+=x.revenue;cur.quantity+=x.quantity;cur.markup+=x.markup;m.set(x.category,cur)});return[...m.values()].sort((a,b)=>b.revenue-a.revenue)},[products]);
 const heat=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)&&dateAllowed(x.date)).forEach(x=>{if(filters.selectedHours.length&&!filters.selectedHours.includes(Number(x.hour)))return;const d=new Date(`${x.date}T00:00:00`),weekday=d.getDay()||7,key=`${weekday}|${x.hour}`,cur=m.get(key)||{weekday,hour:x.hour,revenue:0,orders:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;m.set(key,cur)});return[...m.values()]},[data,range,filters.selectedDates,filters.selectedHours]);
 const totalChannel=channels.reduce((s,x)=>s+x.revenue,0),topProducts=products.slice(0,10),topCategories=categories.slice(0,8);
 const deltas={revenue:filters.compareLFL?change(current.revenue,previous.revenue):null,orders:filters.compareLFL?change(current.orders,previous.orders):null,averageCheck:filters.compareLFL?change(current.averageCheck,previous.averageCheck):null,markup:filters.compareLFL?change(current.markup,previous.markup):null};
 const openDate=(label:string)=>{const row=data?.daily.find(x=>x.date===label);if(!row)return;setDrawer({type:'date',title:fullDate(new Date(`${label}T00:00:00`)),subtitle:'Деталі продажів за вибраний день',metrics:[{label:'Оборот',value:money(Number(row.revenue)||0)},{label:'Чеки',value:num(Number(row.orders)||0)},{label:'Середній чек',value:money(Number(row.averageCheck)||0)},{label:'Націнка',value:money(Number(row.markup)||0)}],action:()=>{toggleDate(label);closeDrawer()}})};
 const clickDate=(state:any)=>{const label=state?.activeLabel;if(label)openDate(String(label))};
 const openChannel=(x:ChannelRow)=>setDrawer({type:'channel',title:x.channel,subtitle:'Структура та ефективність каналу',metrics:[{label:'Оборот',value:money(x.revenue)},{label:'Чеки',value:num(x.orders)},{label:'Середній чек',value:money(x.averageCheck)},{label:'Частка',value:pct(x.share)},{label:'Націнка',value:money(x.markup)},{label:'Націнка %',value:pct(x.revenue?x.markup/x.revenue*100:0)}],action:()=>{toggleChannel(x.channel);closeDrawer()}});
 const openCategory=(x:{category:string;revenue:number;quantity:number;markup:number})=>setDrawer({type:'category',title:x.category,subtitle:'Категорійний зріз за поточними фільтрами',metrics:[{label:'Оборот',value:money(x.revenue)},{label:'Продано',value:`${num(x.quantity)} од.`},{label:'Націнка',value:money(x.markup)},{label:'Націнка %',value:pct(x.revenue?x.markup/x.revenue*100:0)}],action:()=>{toggleCategory(x.category);closeDrawer()}});
 const openProduct=(x:ProductRow)=>setDrawer({type:'product',title:x.productName,subtitle:x.category,metrics:[{label:'Оборот',value:money(x.revenue)},{label:'Продано',value:`${num(x.quantity)} од.`},{label:'Націнка',value:money(x.markup)},{label:'Націнка/од.',value:money(x.quantity?x.markup/x.quantity:0)}],action:()=>{toggleProduct(x.productName);closeDrawer()}});
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8">
  <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex items-center gap-3 text-[#cfeeed]"><BarChart3 size={26}/><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">АНАЛІТИКА ПРОДАЖІВ</p><h1 className="text-4xl font-black md:text-5xl">Продажі</h1></div></div><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
  <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label="Оборот" value={money(current.revenue)} delta={deltas.revenue}/><Kpi icon={ReceiptText} label="Чеки" value={num(current.orders)} delta={deltas.orders}/><Kpi icon={ShoppingBasket} label="Середній чек" value={money(current.averageCheck)} delta={deltas.averageCheck}/><Kpi icon={TrendingUp} label="Націнка" value={money(current.markup)} sub={pct(current.markupPercent)} delta={deltas.markup}/></div>
  <div className="grid gap-6 xl:grid-cols-12"><Panel title="Динаміка продажів" subtitle="Натисни на день для деталей" className="xl:col-span-8"><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.daily.filter(x=>inRange(x.date,range.from,range.to))} onClick={clickDate} className="cursor-pointer"><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="date" tickFormatter={shortDate} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={v=>`${Math.round(Number(v)/1000)}k`} tick={{fill:'rgba(255,255,255,.5)',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} labelFormatter={label=>shortDate(String(label))} formatter={value=>money(Number(value)||0)}/><Area type="monotone" dataKey="revenue" stroke="#cfeeed" fill="#cfeeed" fillOpacity={.14} strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel>
  <Panel title="Канали" subtitle="Клік відкриває деталі" className="xl:col-span-4"><div className="space-y-4">{channels.map(x=>{const active=filters.selectedChannels.includes(x.channel);return <button key={x.channel} onClick={()=>openChannel(x)} className={`block w-full rounded-xl p-2 text-left transition ${active?'bg-[#cfeeed]/12 ring-1 ring-[#cfeeed]/45':'hover:bg-white/[.04]'}`}><div className="mb-2 flex justify-between gap-3"><b>{x.channel}</b><span className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><span className="ml-2 text-xs text-white/40">{pct(x.share)}</span></span></div><div className="h-2 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-[#cfeeed]" style={{width:`${totalChannel?x.revenue/totalChannel*100:0}%`}}/></div></button>})}</div></Panel>
  <Panel title="Теплова карта попиту" subtitle="День × година" className="xl:col-span-7"><Heatmap cells={heat}/></Panel>
  <Panel title="Категорії" subtitle="Клік відкриває деталі" className="xl:col-span-5"><div className="space-y-3">{topCategories.map(x=>{const active=filters.selectedCategories.includes(x.category);return <button key={x.category} onClick={()=>openCategory(x)} className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-left transition ${active?'bg-[#cfeeed]/14 ring-1 ring-[#cfeeed]/45':'bg-black/10 hover:bg-white/[.05]'}`}><span className="font-bold">{x.category}</span><span className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><span className="ml-2 text-xs text-white/40">{num(x.quantity)} од.</span></span></button>})}</div></Panel>
  <Panel title="Топ страв" subtitle="Клік відкриває картку страви" className="xl:col-span-12"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Страва</th><th>Категорія</th><th className="text-right">Кількість</th><th className="text-right">Оборот</th><th className="text-right">Націнка</th></tr></thead><tbody>{topProducts.map((x,i)=>{const active=filters.selectedProducts.includes(x.productName);return <tr key={`${x.productName}-${i}`} onClick={()=>openProduct(x)} className={`cursor-pointer border-b border-white/[.07] transition ${active?'bg-[#cfeeed]/12':'hover:bg-white/[.04]'}`}><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-semibold">{x.productName}</td><td className="text-white/45">{x.category}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{money(x.markup)}</td></tr>})}</tbody></table></div></Panel></div>
 </div><DrilldownDrawer open={!!drawer} eyebrow={drawer?.type==='date'?'ДЕНЬ':drawer?.type==='channel'?'КАНАЛ':drawer?.type==='category'?'КАТЕГОРІЯ':'СТРАВА'} title={drawer?.title||''} subtitle={drawer?.subtitle} metrics={drawer?.metrics} actionLabel="Застосувати як фільтр" onAction={drawer?.action} onClose={closeDrawer}/></div>
}

function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:ReactNode;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}
function Kpi({icon:Icon,label,value,sub,delta}:{icon:any;label:string;value:string;sub?:string;delta:number|null}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div><div className="mt-2 flex items-center justify-between text-xs"><span className="font-bold text-[#cfeeed]/70">{sub||' '}</span><span className={delta===null?'text-white/35':delta>=0?'font-black text-emerald-300':'font-black text-rose-300'}>{delta===null?'—':`${delta>=0?'+':''}${delta.toFixed(1)}%`}</span></div></div>}
