import {useEffect,useMemo,useState}from'react';
import{BarChart3,RefreshCw,ReceiptText,ShoppingBasket,TrendingUp,Utensils,WalletCards}from'lucide-react';
import{Area,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{Payload,aggregate,buildRange,change,fullDate,inRange,money,num,pct,shortDate}from'./sales/data';
import{cleanProductRows,normalizeProductName}from'./sales/semantic';
import{normalizeChannel}from'./sales/channelNames';
import{useFilters}from'./context/FilterContext';
import Heatmap from'./sales/Heatmap';

const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const tooltipStyle={borderRadius:16,border:'1px solid rgba(209,242,240,.18)',background:'rgba(48,5,22,.97)',color:'#fff'};

type ChannelRow={channel:string;revenue:number;orders:number;markup:number;share:number;averageCheck:number};
type ProductRow={productName:string;category:string;quantity:number;revenue:number;markup:number};

export default function SalesDashboardGlobal(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true);
 const{filters,toggleChannel,toggleCategory}=useFilters();
 const load=async()=>{setLoading(true);try{const r=await fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'});const p=await r.json()as Payload;if(Number(p.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(p)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const currentDaily=useMemo(()=>data?data.daily.filter(x=>inRange(x.date,range.from,range.to)):[],[data,range]);
 const previousDaily=useMemo(()=>data&&filters.compareLFL&&filters.period!=='all'?data.daily.filter(x=>inRange(x.date,range.comparisonFrom,range.comparisonTo)):[],[data,filters.compareLFL,filters.period,range]);
 const current=useMemo(()=>aggregate(currentDaily),[currentDaily]),previous=useMemo(()=>aggregate(previousDaily),[previousDaily]);
 const channels=useMemo<ChannelRow[]>(()=>{if(!data)return[];const m=new Map<string,ChannelRow>();data.channelsDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const channel=normalizeChannel(x.channel);if(filters.selectedChannels.length&&!filters.selectedChannels.includes(channel))return;const cur=m.get(channel)||{channel,revenue:0,orders:0,markup:0,share:0,averageCheck:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;cur.markup+=Number(x.markup)||0;m.set(channel,cur)});const total=[...m.values()].reduce((s,x)=>s+x.revenue,0);return[...m.values()].map(x=>({...x,share:total?x.revenue/total*100:0,averageCheck:x.orders?x.revenue/x.orders:0})).sort((a,b)=>b.revenue-a.revenue)},[data,range,filters.selectedChannels]);
 const products=useMemo<ProductRow[]>(()=>{if(!data)return[];let source:any[]=data.productsDaily.filter(x=>inRange(x.date,range.from,range.to));if(filters.hideServiceItems)source=cleanProductRows(source);const map=new Map<string,ProductRow>();source.forEach((x:any)=>{const name=filters.normalizeProducts?normalizeProductName(x.productName):String(x.productName||'').trim();const category=String(x.category||'Без категорії').trim()||'Без категорії';if(filters.selectedCategories.length&&!filters.selectedCategories.includes(category))return;const q=filters.searchQuery.trim().toLowerCase();if(q&&!`${name} ${category}`.toLowerCase().includes(q))return;const key=filters.normalizeProducts?name.toLowerCase():`${x.productCode}|${name}`;const cur=map.get(key)||{productName:name,category,quantity:0,revenue:0,markup:0};cur.quantity+=Number(x.quantity)||0;cur.revenue+=Number(x.revenue)||0;cur.markup+=Number(x.markup)||0;map.set(key,cur)});return[...map.values()].filter(x=>x.quantity>0&&x.revenue>0).sort((a,b)=>b.revenue-a.revenue)},[data,range,filters.hideServiceItems,filters.normalizeProducts,filters.selectedCategories,filters.searchQuery]);
 const categories=useMemo(()=>{const m=new Map<string,{category:string;revenue:number;quantity:number}>();products.forEach(x=>{const cur=m.get(x.category)||{category:x.category,revenue:0,quantity:0};cur.revenue+=x.revenue;cur.quantity+=x.quantity;m.set(x.category,cur)});return[...m.values()].sort((a,b)=>b.revenue-a.revenue)},[products]);
 const heat=useMemo(()=>{if(!data)return[];const m=new Map<string,any>();data.hourlyDaily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const d=new Date(`${x.date}T00:00:00`),weekday=d.getDay()||7,key=`${weekday}|${x.hour}`,cur=m.get(key)||{weekday,hour:x.hour,revenue:0,orders:0};cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;m.set(key,cur)});return[...m.values()]},[data,range]);
 const totalChannel=channels.reduce((s,x)=>s+x.revenue,0),topProducts=products.slice(0,10),topCategories=categories.slice(0,8);
 const deltas={revenue:filters.compareLFL?change(current.revenue,previous.revenue):null,orders:filters.compareLFL?change(current.orders,previous.orders):null,averageCheck:filters.compareLFL?change(current.averageCheck,previous.averageCheck):null,markup:filters.compareLFL?change(current.markup,previous.markup):null};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;
 if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8">
  <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex items-center gap-3 text-[#cfeeed]"><BarChart3 size={26}/><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">АНАЛІТИКА ПРОДАЖІВ</p><h1 className="text-4xl font-black md:text-5xl">Продажі</h1></div></div><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
  <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label="Оборот" value={money(current.revenue)} delta={deltas.revenue}/><Kpi icon={ReceiptText} label="Чеки" value={num(current.orders)} delta={deltas.orders}/><Kpi icon={ShoppingBasket} label="Середній чек" value={money(current.averageCheck)} delta={deltas.averageCheck}/><Kpi icon={TrendingUp} label="Націнка" value={money(current.markup)} sub={pct(current.markupPercent)} delta={deltas.markup}/></div>
  <div className="grid gap-6 xl:grid-cols-12"><Panel title="Динаміка продажів" subtitle={range.label} className="xl:col-span-8"><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><Area data={currentDaily} type="monotone" dataKey="revenue" stroke="#cfeeed" fill="#cfeeed" fillOpacity={.14}/></ResponsiveContainer></div><div className="mt-2 h-0 overflow-hidden"><CartesianGrid/><XAxis/><YAxis/><Tooltip contentStyle={tooltipStyle}/></div></Panel>
  <Panel title="Канали" subtitle="Натисни для глобального фільтра" className="xl:col-span-4"><div className="space-y-4">{channels.map(x=><button key={x.channel} onClick={()=>toggleChannel(x.channel)} className="block w-full text-left"><div className="mb-2 flex justify-between gap-3"><b>{x.channel}</b><span className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><span className="ml-2 text-xs text-white/40">{pct(x.share)}</span></span></div><div className="h-2 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-[#cfeeed]" style={{width:`${totalChannel?x.revenue/totalChannel*100:0}%`}}/></div></button>)}</div></Panel>
  <Panel title="Теплова карта попиту" subtitle="День × година" className="xl:col-span-7"><Heatmap cells={heat}/></Panel>
  <Panel title="Категорії" subtitle="Натисни для глобального фільтра" className="xl:col-span-5"><div className="space-y-3">{topCategories.map(x=><button key={x.category} onClick={()=>toggleCategory(x.category)} className="flex w-full items-center justify-between rounded-xl bg-black/10 px-4 py-3 text-left"><span className="font-bold">{x.category}</span><span className="text-right"><b className="text-[#cfeeed]">{money(x.revenue)}</b><span className="ml-2 text-xs text-white/40">{num(x.quantity)} од.</span></span></button>)}</div></Panel>
  <Panel title="Топ страв" subtitle="З урахуванням глобального пошуку та категорій" className="xl:col-span-12"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">#</th><th>Страва</th><th>Категорія</th><th className="text-right">Кількість</th><th className="text-right">Оборот</th><th className="text-right">Націнка</th></tr></thead><tbody>{topProducts.map((x,i)=><tr key={`${x.productName}-${i}`} className="border-b border-white/[.07]"><td className="py-4 font-black text-[#cfeeed]">{i+1}</td><td className="font-semibold">{x.productName}</td><td className="text-white/45">{x.category}</td><td className="text-right">{num(x.quantity)}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenue)}</td><td className="text-right">{money(x.markup)}</td></tr>)}</tbody></table></div></Panel></div>
 </div></div>
}

function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:any;className?:string}){return <section className={`rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7 ${className}`}><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-white/50">{subtitle}</p>}</div>{children}</section>}
function Kpi({icon:Icon,label,value,sub,delta}:{icon:any;label:string;value:string;sub?:string;delta:number|null}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{label}</p><Icon size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{value}</div><div className="mt-2 flex items-center justify-between text-xs"><span className="font-bold text-[#cfeeed]/70">{sub||' '}</span><span className={delta===null?'text-white/35':delta>=0?'font-black text-emerald-300':'font-black text-rose-300'}>{delta===null?'—':`${delta>=0?'+':''}${delta.toFixed(1)}%`}</span></div></div>}
