import{useEffect,useMemo,useState}from'react';
import{CalendarDays,RefreshCw,ReceiptText,TrendingUp,WalletCards,Lightbulb}from'lucide-react';
import{Payload,buildRange,inRange,money,num,pct,fullDate,shortDate,parseDate}from'./sales/data';
import{loadIntelligence,type IntelligencePayload}from'./sales/intelligence';
import{useFilters}from'./context/FilterContext';
import OperationsHeatmap from'./components/OperationsHeatmap';

type Row={day:number;label:string;days:number;revenue:number;orders:number;markup:number;averageCheck:number;markupPercent:number;revenuePerDay:number;ordersPerDay:number;share:number};
const DATA_URL=`${import.meta.env.BASE_URL||'/'}sales-data.json`;
const DAYS=['Неділя','Понеділок','Вівторок','Середа','Четвер','П’ятниця','Субота'];
const ORDER=[1,2,3,4,5,6,0];
export default function WeekdayDashboard(){
 const[data,setData]=useState<Payload|null>(null),[intel,setIntel]=useState<IntelligencePayload|null>(null),[loading,setLoading]=useState(true);const{filters}=useFilters();
 const load=async()=>{setLoading(true);try{const[s,i]=await Promise.all([fetch(`${DATA_URL}?_=${Date.now()}`,{cache:'no-store'}).then(r=>r.json()as Promise<Payload>),loadIntelligence().catch(()=>null)]);if(Number(s.schemaVersion)!==2)throw Error('schemaVersion 2 required');setData(s);setIntel(i)}catch(e){console.error(e);setData(null)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const range=useMemo(()=>buildRange(filters.period,new Date()),[filters.period]);
 const rows=useMemo<Row[]>(()=>{if(!data)return[];const map=new Map<number,Row>();data.daily.filter(x=>inRange(x.date,range.from,range.to)).forEach(x=>{const day=parseDate(x.date).getDay(),cur=map.get(day)||{day,label:DAYS[day],days:0,revenue:0,orders:0,markup:0,averageCheck:0,markupPercent:0,revenuePerDay:0,ordersPerDay:0,share:0};cur.days++;cur.revenue+=Number(x.revenue)||0;cur.orders+=Number(x.orders)||0;cur.markup+=Number(x.markup)||0;map.set(day,cur)});const total=[...map.values()].reduce((s,x)=>s+x.revenue,0);return ORDER.map(day=>map.get(day)||{day,label:DAYS[day],days:0,revenue:0,orders:0,markup:0,averageCheck:0,markupPercent:0,revenuePerDay:0,ordersPerDay:0,share:0}).map(x=>({...x,averageCheck:x.orders?x.revenue/x.orders:0,markupPercent:x.revenue?x.markup/x.revenue*100:0,revenuePerDay:x.days?x.revenue/x.days:0,ordersPerDay:x.days?x.orders/x.days:0,share:total?x.revenue/total*100:0}))},[data,range]);
 const best=[...rows].sort((a,b)=>b.revenuePerDay-a.revenuePerDay)[0],weak=[...rows].filter(x=>x.days>0).sort((a,b)=>a.revenuePerDay-b.revenuePerDay)[0],tot=rows.reduce((a,x)=>({revenue:a.revenue+x.revenue,orders:a.orders+x.orders,markup:a.markup+x.markup}),{revenue:0,orders:0,markup:0});
 const groups=useMemo(()=>{const make=(days:number[])=>{const s=rows.filter(x=>days.includes(x.day)).reduce((a,x)=>({days:a.days+x.days,revenue:a.revenue+x.revenue,orders:a.orders+x.orders}),{days:0,revenue:0,orders:0});return{...s,revenuePerDay:s.days?s.revenue/s.days:0,ordersPerDay:s.days?s.orders/s.days:0,averageCheck:s.orders?s.revenue/s.orders:0}};return{weekdays:make([1,2,3,4,5]),weekend:make([6,0])}},[rows]);
 const heat=(intel?.heatmap||[]).filter(x=>x.hour>=10&&x.hour<=22),gap=groups.weekdays.revenuePerDay?((groups.weekend.revenuePerDay-groups.weekdays.revenuePerDay)/groups.weekdays.revenuePerDay*100):0;
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e] text-white"><RefreshCw className="animate-spin"/></div>;if(!data)return <div className="flex min-h-screen items-center justify-center bg-[#4d071e]"><button onClick={load} className="rounded-xl bg-[#cfeeed] px-5 py-3 font-bold text-[#5b0b25]">Повторити</button></div>;
 return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#7d1640_0%,#580822_34%,#3c0417_100%)] text-white"><div className="mx-auto max-w-[1600px] px-4 py-7 md:px-8"><header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-[10px] uppercase tracking-[.24em] text-white/45">АНАЛІТИКА ПРОДАЖІВ</p><h1 className="mt-2 text-4xl font-black text-[#d8f4f2] md:text-5xl">Дні тижня</h1><p className="mt-3 text-sm font-semibold text-[#cfeeed]/75">{range.label}{range.from&&range.to?` · ${fullDate(range.from)} — ${fullDate(range.to)}`:` · ${shortDate(data.period.from)} — ${shortDate(data.period.to)}`}</p></div><button onClick={load} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/10 bg-white/[.06] px-4 py-3 text-sm font-bold"><RefreshCw size={17}/> Оновити дані</button></header>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><K icon={WalletCards} l="Оборот" v={money(tot.revenue)}/><K icon={ReceiptText} l="Чеки" v={num(tot.orders)}/><K icon={TrendingUp} l="Найсильніший день" v={best?.label||'—'} s={best?money(best.revenuePerDay)+'/день':undefined}/><K icon={CalendarDays} l="День для активації" v={weak?.label||'—'} s={weak?money(weak.revenuePerDay)+'/день':undefined}/></div>
 <div className="mb-6 grid gap-4 lg:grid-cols-3"><Group title="Будні" value={groups.weekdays.revenuePerDay} orders={groups.weekdays.ordersPerDay} check={groups.weekdays.averageCheck}/><Group title="Вихідні" value={groups.weekend.revenuePerDay} orders={groups.weekend.ordersPerDay} check={groups.weekend.averageCheck}/><div className="rounded-2xl border border-[#cfeeed]/20 bg-[#cfeeed]/10 p-5"><div className="flex items-center gap-2 text-[#cfeeed]"><Lightbulb size={18}/><p className="text-xs font-black uppercase">Операційний сигнал</p></div><p className="mt-3 text-lg font-black">{gap>=0?`Вихідні сильніші на ${gap.toFixed(1)}%`:`Будні сильніші на ${Math.abs(gap).toFixed(1)}%`}</p><p className="mt-2 text-sm text-white/55">{gap>=0?'Плануй максимальну готовність кухні й команди на вихідні.':'Основний попит формується у будні — промо на вихідні мають бути точковими.'}</p></div></div>
 <section className="rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><div className="mb-5"><h2 className="text-2xl font-black text-[#d8f4f2]">Ефективність днів тижня</h2><p className="mt-1 text-sm text-white/50">Середні показники на один фактичний день, щоб неповні тижні не спотворювали рейтинг</p></div><div className="grid gap-3 lg:grid-cols-7">{rows.map(x=><div key={x.day} className={`rounded-2xl border p-4 ${x.day===best?.day?'border-[#cfeeed] bg-[#cfeeed] text-[#531027]':'border-white/10 bg-black/10'}`}><p className="text-xs font-black uppercase opacity-60">{x.label}</p><div className="mt-3 text-2xl font-black">{money(x.revenuePerDay)}</div><p className="mt-1 text-xs opacity-60">{num(x.ordersPerDay)} чеків/день</p><div className="mt-4 border-t border-current/10 pt-3 text-xs"><p>Сер. чек: <b>{money(x.averageCheck)}</b></p><p className="mt-1">Націнка: <b>{pct(x.markupPercent)}</b></p><p className="mt-1">Частка: <b>{pct(x.share)}</b></p></div></div>)}</div></section>
 {heat.length>0&&<div className="mt-5"><OperationsHeatmap data={heat} title="Коли саме формуються сильні та слабкі дні" subtitle="Матриця чеків за днями тижня та годинами роботи" metric="orders"/></div>}
 <section className="mt-5 rounded-[28px] border border-white/10 bg-white/[.055] p-5 md:p-7"><h2 className="text-2xl font-black text-[#d8f4f2]">Рейтинг днів</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[10px] uppercase tracking-[.12em] text-white/35"><th className="pb-4">День</th><th className="text-right">Днів у вибірці</th><th className="text-right">Оборот/день</th><th className="text-right">Чеки/день</th><th className="text-right">Середній чек</th><th className="text-right">Націнка %</th><th className="text-right">Частка обороту</th></tr></thead><tbody>{[...rows].sort((a,b)=>b.revenuePerDay-a.revenuePerDay).map(x=><tr key={x.day} className="border-b border-white/[.07]"><td className="py-4 font-bold">{x.label}</td><td className="text-right">{x.days}</td><td className="text-right font-black text-[#cfeeed]">{money(x.revenuePerDay)}</td><td className="text-right">{num(x.ordersPerDay)}</td><td className="text-right">{money(x.averageCheck)}</td><td className="text-right">{pct(x.markupPercent)}</td><td className="text-right">{pct(x.share)}</td></tr>)}</tbody></table></div></section></div></div>}
function K({icon:I,l,v,s}:{icon:any;l:string;v:string;s?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><div className="flex items-center justify-between text-white/45"><p className="text-xs font-black uppercase">{l}</p><I size={18}/></div><div className="mt-2 text-3xl font-black text-[#d8f4f2]">{v}</div>{s&&<div className="mt-1 text-xs font-bold text-[#cfeeed]/70">{s}</div>}</div>}
function Group({title,value,orders,check}:{title:string;value:number;orders:number;check:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-xs font-black uppercase text-white/45">{title}</p><div className="mt-2 text-2xl font-black text-[#d8f4f2]">{money(value)}/день</div><p className="mt-2 text-xs text-white/50">{num(orders)} чеків/день · {money(check)} середній чек</p></div>}
